In [1]:
import duckdb
import polars as pl
import numpy as np
import pendulum
from pathlib import Path

data_dir = Path("../data/lastfm/listening")
db = duckdb.read_json(data_dir/"*.jsonl")
df = db.pl()

df = df.with_columns(
    pl.from_epoch(
        pl.col("date_played_unix"), time_unit="s"
    ).alias("track_played_utc")
)

print("Raw data:", df.shape)

df = df.unique("date_played_unix") # Not so exact with which duplicate gets removed
print("Duplicate timestamps removed:", df.unique("date_played_unix").shape)
df = df.with_columns(
    artist_name = pl.col("artist_name").str.to_lowercase(),
    track_name = pl.col("track_name").str.to_lowercase(),
    album_name = pl.col("album_name").str.to_lowercase()
)
df.head()

Raw data: (110513, 8)
Duplicate timestamps removed: (108066, 8)

shape: (5, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ artist_nam ┆ artist_mbi ┆ album_name ┆ album_mbi ┆ track_nam ┆ track_mbi ┆ date_play ┆ track_pla │
│ e          ┆ d          ┆ ---        ┆ d         ┆ e         ┆ d         ┆ ed_unix   ┆ yed_utc   │
│ ---        ┆ ---        ┆ str        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ str        ┆            ┆ str       ┆ str       ┆ str       ┆ i64       ┆ datetime[ │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ μs]       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ elias      ┆            ┆ close (the ┆           ┆ close -   ┆           ┆ 174228378 ┆ 2025-03-1 │
│ rønnenfelt ┆            ┆ dare       ┆           ┆ the dare  ┆           ┆ 6         ┆ 8         │
│            ┆            ┆ remix)     ┆           ┆ remix     ┆           ┆           ┆ 07:43:06  │
│ macabre    ┆            ┆ out with   ┆           ┆ till the  ┆           ┆ 170981542 ┆ 2024-03-0 │
│ plaza      ┆            ┆ the old in ┆           ┆ wheels    ┆           ┆ 6         ┆ 7         │
│            ┆            ┆ with the   ┆           ┆ fall off  ┆           ┆           ┆ 12:43:46  │
│            ┆            ┆ t…         ┆           ┆           ┆           ┆           ┆           │
│ desire     ┆            ┆ desire     ┆ 8af35ae0- ┆ under     ┆ 17579de2- ┆ 173730456 ┆ 2025-01-1 │
│            ┆            ┆            ┆ 96af-453c ┆ your      ┆ f1e4-4e0e ┆ 6         ┆ 9         │
│            ┆            ┆            ┆ -8e6e-304 ┆ spell     ┆ -a4c7-e18 ┆           ┆ 16:36:06  │
│            ┆            ┆            ┆ 7ca…      ┆           ┆ 106…      ┆           ┆           │
│ tracey     ┆ 4e40592a-3 ┆ wand of    ┆           ┆ wand of   ┆           ┆ 167766491 ┆ 2023-03-0 │
│ brakes     ┆ 581-42f1-b ┆ tens       ┆           ┆ tens      ┆           ┆ 5         ┆ 1         │
│            ┆ 6e8-ced9ac ┆            ┆           ┆           ┆           ┆           ┆ 10:01:55  │
│            ┆ …          ┆            ┆           ┆           ┆           ┆           ┆           │
│ alex g     ┆ 7df4c4de-3 ┆ trick      ┆ 141c833b- ┆ sarah     ┆ 70ad2ffc- ┆ 164439433 ┆ 2022-02-0 │
│            ┆ 181-4a69-b ┆            ┆ c3c4-4e12 ┆           ┆ 5980-4f44 ┆ 1         ┆ 9         │
│            ┆ d36-9d6639 ┆            ┆ -8157-bf5 ┆           ┆ -b43b-a8e ┆           ┆ 08:12:11  │
│            ┆ …          ┆            ┆ 435…      ┆           ┆ dc3…      ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

## Seasonal patterns — do you listen to certain artists more in winter vs. summer?

In [2]:
df_ = df.filter(pl.col("track_played_utc").dt.year() == 2025)

In [3]:
df_pivot = (
    df_
    .group_by(
        pl.col("artist_name"), 
        pl.col("track_played_utc").dt.strftime("%B").alias("month"),
        pl.col("track_played_utc").dt.month().alias("month_idx")
    )
    .agg(
        scrobbles = pl.len()
    )
    .sort(pl.col("month_idx"), descending=False)
    .pivot(
        on="month",
        index="artist_name",
        values="scrobbles",
        aggregate_function="sum"
    )
)
df_pivot

shape: (1_553, 13)
┌──────────────────┬─────────┬──────────┬───────┬───┬───────────┬─────────┬──────────┬──────────┐
│ artist_name      ┆ January ┆ February ┆ March ┆ … ┆ September ┆ October ┆ November ┆ December │
│ ---              ┆ ---     ┆ ---      ┆ ---   ┆   ┆ ---       ┆ ---     ┆ ---      ┆ ---      │
│ str              ┆ u32     ┆ u32      ┆ u32   ┆   ┆ u32       ┆ u32     ┆ u32      ┆ u32      │
╞══════════════════╪═════════╪══════════╪═══════╪═══╪═══════════╪═════════╪══════════╪══════════╡
│ infime           ┆ 1       ┆ 1        ┆ 1     ┆ … ┆ 0         ┆ 0       ┆ 0        ┆ 0        │
│ night tapes      ┆ 2       ┆ 1        ┆ 0     ┆ … ┆ 0         ┆ 0       ┆ 0        ┆ 1        │
│ eera             ┆ 17      ┆ 11       ┆ 25    ┆ … ┆ 0         ┆ 0       ┆ 1        ┆ 0        │
│ beth gibbons     ┆ 2       ┆ 1        ┆ 1     ┆ … ┆ 1         ┆ 0       ┆ 0        ┆ 0        │
│ wet leg          ┆ 3       ┆ 1        ┆ 9     ┆ … ┆ 0         ┆ 0       ┆ 0        ┆ 0        │
│ …                ┆ …       ┆ …        ┆ …     ┆ … ┆ …         ┆ …       ┆ …        ┆ …        │
│ rome rome        ┆ 0       ┆ 0        ┆ 0     ┆ … ┆ 0         ┆ 0       ┆ 0        ┆ 1        │
│ lil ugly mane    ┆ 0       ┆ 0        ┆ 0     ┆ … ┆ 0         ┆ 0       ┆ 0        ┆ 9        │
│ adamn killa      ┆ 0       ┆ 0        ┆ 0     ┆ … ┆ 0         ┆ 0       ┆ 0        ┆ 1        │
│ black tape for a ┆ 0       ┆ 0        ┆ 0     ┆ … ┆ 0         ┆ 0       ┆ 0        ┆ 1        │
│ blue girl        ┆         ┆          ┆       ┆   ┆           ┆         ┆          ┆          │
│ r!r!riot         ┆ 0       ┆ 0        ┆ 0     ┆ … ┆ 0         ┆ 0       ┆ 0        ┆ 2        │
└──────────────────┴─────────┴──────────┴───────┴───┴───────────┴─────────┴──────────┴──────────┘

In [4]:
n = 20
df_top_n_artists = (
    df_
    .group_by(
        pl.col("artist_name"), 
        # pl.col("track_played_utc").dt.strftime("%B").alias("month"),
        # pl.col("track_played_utc").dt.month().alias("month_idx")
    )
    .agg(
        scrobbles = pl.len()
    )
    .sort(pl.col("scrobbles"), descending=True)
).head(20)

df_pivot.join(df_top_n_artists, on="artist_name").sort("scrobbles", descending=True)

shape: (20, 14)
┌──────────────┬─────────┬──────────┬───────┬───┬─────────┬──────────┬──────────┬───────────┐
│ artist_name  ┆ January ┆ February ┆ March ┆ … ┆ October ┆ November ┆ December ┆ scrobbles │
│ ---          ┆ ---     ┆ ---      ┆ ---   ┆   ┆ ---     ┆ ---      ┆ ---      ┆ ---       │
│ str          ┆ u32     ┆ u32      ┆ u32   ┆   ┆ u32     ┆ u32      ┆ u32      ┆ u32       │
╞══════════════╪═════════╪══════════╪═══════╪═══╪═════════╪══════════╪══════════╪═══════════╡
│ bladee       ┆ 26      ┆ 53       ┆ 31    ┆ … ┆ 42      ┆ 11       ┆ 13       ┆ 459       │
│ dean blunt   ┆ 0       ┆ 7        ┆ 86    ┆ … ┆ 66      ┆ 8        ┆ 14       ┆ 411       │
│ bassvictim   ┆ 5       ┆ 90       ┆ 35    ┆ … ┆ 65      ┆ 73       ┆ 26       ┆ 369       │
│ astrid sonne ┆ 4       ┆ 2        ┆ 36    ┆ … ┆ 9       ┆ 8        ┆ 4        ┆ 301       │
│ vegyn        ┆ 5       ┆ 6        ┆ 2     ┆ … ┆ 10      ┆ 11       ┆ 4        ┆ 301       │
│ …            ┆ …       ┆ …        ┆ …     ┆ … ┆ …       ┆ …        ┆ …        ┆ …         │
│ mj lenderman ┆ 0       ┆ 6        ┆ 129   ┆ … ┆ 5       ┆ 1        ┆ 4        ┆ 174       │
│ jane remover ┆ 36      ┆ 22       ┆ 17    ┆ … ┆ 0       ┆ 3        ┆ 2        ┆ 167       │
│ blood orange ┆ 0       ┆ 0        ┆ 0     ┆ … ┆ 4       ┆ 3        ┆ 10       ┆ 166       │
│ 1tbsp        ┆ 10      ┆ 31       ┆ 5     ┆ … ┆ 1       ┆ 2        ┆ 1        ┆ 159       │
│ 2hollis      ┆ 26      ┆ 13       ┆ 9     ┆ … ┆ 1       ┆ 1        ┆ 1        ┆ 159       │
└──────────────┴─────────┴──────────┴───────┴───┴─────────┴──────────┴──────────┴───────────┘

In [5]:
(
    df_
    .group_by(
        pl.col("artist_name"), 
        pl.col("track_played_utc").dt.strftime("%B").alias("month"),
        pl.col("track_played_utc").dt.month().alias("month_idx")
    )
    .agg(
        scrobbles = pl.len()
    )
)

shape: (3_872, 4)
┌───────────────────────┬───────────┬───────────┬───────────┐
│ artist_name           ┆ month     ┆ month_idx ┆ scrobbles │
│ ---                   ┆ ---       ┆ ---       ┆ ---       │
│ str                   ┆ str       ┆ i8        ┆ u32       │
╞═══════════════════════╪═══════════╪═══════════╪═══════════╡
│ matt maltese          ┆ March     ┆ 3         ┆ 1         │
│ yehezkel raz          ┆ February  ┆ 2         ┆ 1         │
│ misha panfilov        ┆ September ┆ 9         ┆ 6         │
│ oneohtrix point never ┆ December  ┆ 12        ┆ 1         │
│ tevvez                ┆ June      ┆ 6         ┆ 1         │
│ …                     ┆ …         ┆ …         ┆ …         │
│ huerco s.             ┆ June      ┆ 6         ┆ 1         │
│ axlr                  ┆ February  ┆ 2         ┆ 1         │
│ purient               ┆ August    ┆ 8         ┆ 1         │
│ the truth             ┆ June      ┆ 6         ┆ 3         │
│ mall grab             ┆ November  ┆ 11        ┆ 4         │
└───────────────────────┴───────────┴───────────┴───────────┘

## "Throwback" plays — replaying old favorites after a long gap

In [6]:
# # Cumulative listening per track, so each record gets a number representing the n'th time of listening to a track.
# bv = (
#     df.sort(pl.col("date_played_unix"), descending=False)
#     .filter(pl.col("track_played_utc").dt.year() == year)
#     .filter(pl.col("artist_name") == "bassvictim")
#     .filter(pl.col("track_name").len().over("track_name") > 10)
#     .with_columns(
#         track_nth_scrobble = pl.col("track_name").cum_count().over(pl.col("track_name"))
#     )
# )
# bv.head()

In [7]:
(
    df
    .sort(pl.col("track_played_utc"), descending=False)
    .with_columns(
        last_played_delta = (
            pl.col("track_played_utc") - pl.col("track_played_utc").shift(1).over("track_name")
            ).dt.total_days(fractional=True).fill_null(0).ceil()
    )
).filter(pl.col("artist_name") == "bladee")

shape: (4_356, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ artist_na ┆ artist_mb ┆ album_nam ┆ album_mbi ┆ … ┆ track_mbi ┆ date_play ┆ track_pla ┆ last_pla │
│ me        ┆ id        ┆ e         ┆ d         ┆   ┆ d         ┆ ed_unix   ┆ yed_utc   ┆ yed_delt │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ a        │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ i64       ┆ datetime[ ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ μs]       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ bladee    ┆ cd689e77- ┆ drama     ┆           ┆ … ┆           ┆ 162149411 ┆ 2021-05-2 ┆ 0.0      │
│           ┆ dfdd-4f81 ┆ (feat.    ┆           ┆   ┆           ┆ 4         ┆ 0         ┆          │
│           ┆ -b50c-5e5 ┆ charli    ┆           ┆   ┆           ┆           ┆ 07:01:54  ┆          │
│           ┆ a3f…      ┆ xcx)      ┆           ┆   ┆           ┆           ┆           ┆          │
│ bladee    ┆ cd689e77- ┆ gluee     ┆ 250bafde- ┆ … ┆           ┆ 162149449 ┆ 2021-05-2 ┆ 0.0      │
│           ┆ dfdd-4f81 ┆           ┆ fd0c-4490 ┆   ┆           ┆ 5         ┆ 0         ┆          │
│           ┆ -b50c-5e5 ┆           ┆ -a728-5f7 ┆   ┆           ┆           ┆ 07:08:15  ┆          │
│           ┆ a3f…      ┆           ┆ 41f…      ┆   ┆           ┆           ┆           ┆          │
│ bladee    ┆ cd689e77- ┆ working   ┆ 587b563c- ┆ … ┆ 22de2b38- ┆ 162149464 ┆ 2021-05-2 ┆ 0.0      │
│           ┆ dfdd-4f81 ┆ on dying  ┆ 73ff-4d81 ┆   ┆ a027-49fe ┆ 4         ┆ 0         ┆          │
│           ┆ -b50c-5e5 ┆           ┆ -b669-b49 ┆   ┆ -8e99-c30 ┆           ┆ 07:10:44  ┆          │
│           ┆ a3f…      ┆           ┆ a2e…      ┆   ┆ 809…      ┆           ┆           ┆          │
│ bladee    ┆ cd689e77- ┆ red light ┆ 725f97cb- ┆ … ┆ 404d136c- ┆ 162149477 ┆ 2021-05-2 ┆ 0.0      │
│           ┆ dfdd-4f81 ┆           ┆ 5e7a-4bbb ┆   ┆ 174c-4cb5 ┆ 2         ┆ 0         ┆          │
│           ┆ -b50c-5e5 ┆           ┆ -be43-c65 ┆   ┆ -9fb0-1e8 ┆           ┆ 07:12:52  ┆          │
│           ┆ a3f…      ┆           ┆ 004…      ┆   ┆ 859…      ┆           ┆           ┆          │
│ bladee    ┆ cd689e77- ┆ working   ┆ 587b563c- ┆ … ┆ 22de2b38- ┆ 162149893 ┆ 2021-05-2 ┆ 1.0      │
│           ┆ dfdd-4f81 ┆ on dying  ┆ 73ff-4d81 ┆   ┆ a027-49fe ┆ 2         ┆ 0         ┆          │
│           ┆ -b50c-5e5 ┆           ┆ -b669-b49 ┆   ┆ -8e99-c30 ┆           ┆ 08:22:12  ┆          │
│           ┆ a3f…      ┆           ┆ a2e…      ┆   ┆ 809…      ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ bladee    ┆ cd689e77- ┆ love is a ┆ 3540f010- ┆ … ┆ 6253d641- ┆ 177428368 ┆ 2026-03-2 ┆ 0.0      │
│           ┆ dfdd-4f81 ┆ state     ┆ 4c99-4c9e ┆   ┆ 5088-4908 ┆ 7         ┆ 3         ┆          │
│           ┆ -b50c-5e5 ┆           ┆ -80e1-3db ┆   ┆ -96df-100 ┆           ┆ 16:34:47  ┆          │
│           ┆ a3f…      ┆           ┆ a8f…      ┆   ┆ b4e…      ┆           ┆           ┆          │
│ bladee    ┆ cd689e77- ┆ eversince ┆ 96e5ccf7- ┆ … ┆ ecd0d043- ┆ 177428391 ┆ 2026-03-2 ┆ 517.0    │
│           ┆ dfdd-4f81 ┆           ┆ 2ba9-4f94 ┆   ┆ fa8e-44e1 ┆ 4         ┆ 3         ┆          │
│           ┆ -b50c-5e5 ┆           ┆ -944d-79c ┆   ┆ -926b-94e ┆           ┆ 16:38:34  ┆          │
│           ┆ a3f…      ┆           ┆ a01…      ┆   ┆ 108…      ┆           ┆           ┆          │
│ bladee    ┆ cd689e77- ┆ sesame    ┆ 2c0a269b- ┆ … ┆ 1907b9ad- ┆ 177435599 ┆ 2026-03-2 ┆ 26.0     │
│           ┆ dfdd-4f81 ┆ street    ┆ 535a-47fe ┆   ┆ 2964-4889 ┆ 5         ┆ 4         ┆          │
│           ┆ -b50c-5e5 ┆           ┆ -97b2-fa4 ┆   ┆ -9df3-be4 ┆           ┆ 12:39:55  ┆          │
│           ┆ a3f…      ┆           ┆ d65…      ┆   ┆ 4ae…      ┆           ┆           ┆          │
│ bladee    ┆ cd689e77- ┆ eversince ┆ 96e5ccf7- ┆ … ┆ 1cb62976- ┆ 177436071 ┆ 2026-03-2 ┆ 19.0     │
│           ┆ dfdd-4f81 ┆           ┆ 2ba9-4f94 ┆   ┆ c4a5-4fd5 ┆ 0         ┆ 4         ┆          │
│           ┆ -b50c-5e5 ┆           ┆ -944d-79c ┆   ┆ -8319-20e ┆           ┆ 13:58:30  ┆          │
│           ┆ a3f…      ┆           ┆ a01…      ┆   ┆ 653…      ┆           ┆           ┆          │
│ bladee    ┆ cd689e77- ┆ love is a ┆ 3540f010- ┆ … ┆ 84dfc956- ┆ 177444911 ┆ 2026-03-2 ┆ 2.0      │
│           ┆ dfdd-4f81 ┆ state     ┆ 4c99-4c9e ┆   ┆ 1fe4-4f67 ┆ 8         ┆ 5         ┆          │
│           ┆ -b50c-5e5 ┆           ┆ -80e1-3db ┆   ┆ -a846-bee ┆           ┆ 14:31:58  ┆          │
│           ┆ a3f…      ┆           ┆ a8f…      ┆   ┆ a7c…      ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [14]:
(
    df
    .filter(pl.col("track_played_utc").dt.year() == 2025)
    .group_by(pl.col("track_name"), pl.col("artist_name"))
    .agg(
        n_scrobbles = pl.len(),
        first_played = pl.col("track_played_utc").min(),
        last_played = pl.col("track_played_utc").max(),
    )
    .sort(pl.col("n_scrobbles"), descending=True)
)

shape: (5_723, 5)
┌──────────────────────┬─────────────┬─────────────┬─────────────────────┬─────────────────────┐
│ track_name           ┆ artist_name ┆ n_scrobbles ┆ first_played        ┆ last_played         │
│ ---                  ┆ ---         ┆ ---         ┆ ---                 ┆ ---                 │
│ str                  ┆ str         ┆ u32         ┆ datetime[μs]        ┆ datetime[μs]        │
╞══════════════════════╪═════════════╪═════════════╪═════════════════════╪═════════════════════╡
│ 5                    ┆ dean blunt  ┆ 59          ┆ 2025-02-14 10:02:11 ┆ 2025-12-17 16:14:16 │
│ flash                ┆ 2hollis     ┆ 47          ┆ 2025-04-04 12:02:50 ┆ 2025-12-01 14:47:24 │
│ react [r tyler edit] ┆ dj_dave     ┆ 46          ┆ 2025-01-23 16:16:02 ┆ 2025-12-15 17:26:52 │
│ bluey vuitton        ┆ babyfather  ┆ 44          ┆ 2025-09-28 09:15:03 ┆ 2025-11-24 15:51:20 │
│ woman lake           ┆ snuggle     ┆ 43          ┆ 2025-06-17 07:23:51 ┆ 2025-12-18 07:36:53 │
│ …                    ┆ …           ┆ …           ┆ …                   ┆ …                   │
│ starjumps            ┆ earthmelon  ┆ 1           ┆ 2025-08-10 13:06:07 ┆ 2025-08-10 13:06:07 │
│ noblest strive       ┆ bladee      ┆ 1           ┆ 2025-01-08 15:53:19 ┆ 2025-01-08 15:53:19 │
│ (=o_o=)              ┆ polygonia   ┆ 1           ┆ 2025-05-10 10:56:12 ┆ 2025-05-10 10:56:12 │
│ arroyo seco parkway  ┆ elijah fox  ┆ 1           ┆ 2025-01-13 10:43:20 ┆ 2025-01-13 10:43:20 │
│ petrol bliss         ┆ choker      ┆ 1           ┆ 2025-11-19 13:40:16 ┆ 2025-11-19 13:40:16 │
└──────────────────────┴─────────────┴─────────────┴─────────────────────┴─────────────────────┘

In [16]:
df_artists = (
    df
    .filter(pl.col("track_played_utc").dt.year() == 2025)
    .group_by(pl.col("artist_name"), pl.col("track_name"))
    .agg(
      track_scrobbles = pl.len(), # scrobbles per track
    )
    .with_columns(
      artist_scrobbles=pl.col("track_scrobbles").sum().over("artist_name") # total artist scrobbles
    )
    .sort(pl.col("artist_scrobbles"), descending=True)
)
top_n_artists = df_artists.select("artist_name").unique(maintain_order=True).head(25)
df_top_n_artists = ( 
    df_artists
    .join(top_n_artists, on="artist_name", how="semi") 
    .sort("track_scrobbles", descending=True)
)