In [2]:
import duckdb
import polars as pl
import numpy as np
import pendulum
from pathlib import Path

data_dir = Path("../data/lastfm/listening")
db = duckdb.read_json(data_dir/"*.jsonl")
df = db.pl()

df = df.with_columns(
    pl.from_epoch(
        pl.col("date_played_unix"), time_unit="s"
    ).alias("track_played_utc")
)

print("Raw data:", df.shape)

df = df.unique("date_played_unix") # Not so exact with which duplicate gets removed
print("Duplicate timestamps removed:", df.unique("date_played_unix").shape)
df = df.with_columns(
    artist_name = pl.col("artist_name").str.to_lowercase(),
    track_name = pl.col("track_name").str.to_lowercase(),
    album_name = pl.col("album_name").str.to_lowercase()
)
df.head()

Raw data: (110513, 8)
Duplicate timestamps removed: (108066, 8)

shape: (5, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ artist_nam ┆ artist_mbi ┆ album_name ┆ album_mbi ┆ track_nam ┆ track_mbi ┆ date_play ┆ track_pla │
│ e          ┆ d          ┆ ---        ┆ d         ┆ e         ┆ d         ┆ ed_unix   ┆ yed_utc   │
│ ---        ┆ ---        ┆ str        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ str        ┆            ┆ str       ┆ str       ┆ str       ┆ i64       ┆ datetime[ │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ μs]       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ aldn       ┆ fa01a34e-0 ┆ ifls       ┆ 15020146- ┆ ifls      ┆ cb2297f2- ┆ 166521599 ┆ 2022-10-0 │
│            ┆ 5f3-424c-8 ┆            ┆ 9301-457c ┆           ┆ a1fc-47f0 ┆ 0         ┆ 8         │
│            ┆ fd0-390840 ┆            ┆ -b45e-f24 ┆           ┆ -9f4a-1d0 ┆           ┆ 07:59:50  │
│            ┆ …          ┆            ┆ 504…      ┆           ┆ 780…      ┆           ┆           │
│ dijon      ┆ cceea21d-f ┆ absolutely ┆ 7fc99d84- ┆ big       ┆ 1ca0c4d4- ┆ 170981726 ┆ 2024-03-0 │
│            ┆ 3ec-4586-b ┆            ┆ befc-4fca ┆ mike's    ┆ 5dc8-4e4d ┆ 6         ┆ 7         │
│            ┆ e7a-d2e939 ┆            ┆ -b29f-a57 ┆           ┆ -9109-2d3 ┆           ┆ 13:14:26  │
│            ┆ …          ┆            ┆ 11a…      ┆           ┆ eff…      ┆           ┆           │
│ joji       ┆ 8264722b-d ┆ smithereen ┆ e26e8cbc- ┆ night     ┆           ┆ 166767204 ┆ 2022-11-0 │
│            ┆ f00-467a-8 ┆ s          ┆ db4c-422a ┆ rider     ┆           ┆ 0         ┆ 5         │
│            ┆ 58e-5c97cd ┆            ┆ -a171-f00 ┆           ┆           ┆           ┆ 18:14:00  │
│            ┆ …          ┆            ┆ 80a…      ┆           ┆           ┆           ┆           │
│ tyler, the ┆            ┆ chromakopi ┆           ┆ like him  ┆           ┆ 173885723 ┆ 2025-02-0 │
│ creator    ┆            ┆ a          ┆           ┆ (feat.    ┆           ┆ 9         ┆ 6         │
│            ┆            ┆            ┆           ┆ lola      ┆           ┆           ┆ 15:53:59  │
│            ┆            ┆            ┆           ┆ young)    ┆           ┆           ┆           │
│ dimitri    ┆ c5931849-7 ┆ disco:wax  ┆           ┆ stampede  ┆           ┆ 165779151 ┆ 2022-07-1 │
│ vegas &    ┆ c9d-465e-b ┆ presents:  ┆           ┆ - major   ┆           ┆ 3         ┆ 4         │
│ like mike  ┆ 717-29e2af ┆ remixes    ┆           ┆ lazer x   ┆           ┆           ┆ 09:38:33  │
│            ┆ …          ┆ pa…        ┆           ┆ p.a.f…    ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

## Seasonal patterns — do you listen to certain artists more in winter vs. summer?

In [14]:
df_ = df.filter(pl.col("track_played_utc").dt.year() == 2025)

In [24]:
df_pivot = (
    df_
    .group_by(
        pl.col("artist_name"), 
        pl.col("track_played_utc").dt.strftime("%B").alias("month"),
        pl.col("track_played_utc").dt.month().alias("month_idx")
    )
    .agg(
        scrobbles = pl.len()
    )
    .sort(pl.col("month_idx"), descending=False)
    .pivot(
        on="month",
        index="artist_name",
        values="scrobbles",
        aggregate_function="sum"
    )
)
df_pivot

shape: (1_553, 13)
┌──────────────────┬─────────┬──────────┬───────┬───┬───────────┬─────────┬──────────┬──────────┐
│ artist_name      ┆ January ┆ February ┆ March ┆ … ┆ September ┆ October ┆ November ┆ December │
│ ---              ┆ ---     ┆ ---      ┆ ---   ┆   ┆ ---       ┆ ---     ┆ ---      ┆ ---      │
│ str              ┆ u32     ┆ u32      ┆ u32   ┆   ┆ u32       ┆ u32     ┆ u32      ┆ u32      │
╞══════════════════╪═════════╪══════════╪═══════╪═══╪═══════════╪═════════╪══════════╪══════════╡
│ oklou            ┆ 20      ┆ 43       ┆ 5     ┆ … ┆ 0         ┆ 3       ┆ 6        ┆ 1        │
│ frost children   ┆ 6       ┆ 2        ┆ 5     ┆ … ┆ 1         ┆ 0       ┆ 0        ┆ 0        │
│ tchami           ┆ 1       ┆ 0        ┆ 0     ┆ … ┆ 0         ┆ 0       ┆ 0        ┆ 0        │
│ mad keys         ┆ 20      ┆ 6        ┆ 2     ┆ … ┆ 0         ┆ 0       ┆ 0        ┆ 0        │
│ pretty sick      ┆ 2       ┆ 0        ┆ 0     ┆ … ┆ 0         ┆ 0       ┆ 0        ┆ 0        │
│ …                ┆ …       ┆ …        ┆ …     ┆ … ┆ …         ┆ …       ┆ …        ┆ …        │
│ skee mask        ┆ 0       ┆ 0        ┆ 0     ┆ … ┆ 0         ┆ 0       ┆ 0        ┆ 1        │
│ vjac0b           ┆ 0       ┆ 0        ┆ 0     ┆ … ┆ 0         ┆ 0       ┆ 0        ┆ 1        │
│ black tape for a ┆ 0       ┆ 0        ┆ 0     ┆ … ┆ 0         ┆ 0       ┆ 0        ┆ 1        │
│ blue girl        ┆         ┆          ┆       ┆   ┆           ┆         ┆          ┆          │
│ self esteem      ┆ 0       ┆ 0        ┆ 0     ┆ … ┆ 0         ┆ 0       ┆ 0        ┆ 3        │
│ tiga             ┆ 0       ┆ 0        ┆ 0     ┆ … ┆ 0         ┆ 0       ┆ 0        ┆ 16       │
└──────────────────┴─────────┴──────────┴───────┴───┴───────────┴─────────┴──────────┴──────────┘

In [29]:
n = 20
df_top_n_artists = (
    df_
    .group_by(
        pl.col("artist_name"), 
        # pl.col("track_played_utc").dt.strftime("%B").alias("month"),
        # pl.col("track_played_utc").dt.month().alias("month_idx")
    )
    .agg(
        scrobbles = pl.len()
    )
    .sort(pl.col("scrobbles"), descending=True)
).head(20)

df_pivot.join(df_top_n_artists, on="artist_name").sort("scrobbles", descending=True)

shape: (20, 14)
┌──────────────┬─────────┬──────────┬───────┬───┬─────────┬──────────┬──────────┬───────────┐
│ artist_name  ┆ January ┆ February ┆ March ┆ … ┆ October ┆ November ┆ December ┆ scrobbles │
│ ---          ┆ ---     ┆ ---      ┆ ---   ┆   ┆ ---     ┆ ---      ┆ ---      ┆ ---       │
│ str          ┆ u32     ┆ u32      ┆ u32   ┆   ┆ u32     ┆ u32      ┆ u32      ┆ u32       │
╞══════════════╪═════════╪══════════╪═══════╪═══╪═════════╪══════════╪══════════╪═══════════╡
│ bladee       ┆ 26      ┆ 53       ┆ 31    ┆ … ┆ 42      ┆ 11       ┆ 13       ┆ 459       │
│ dean blunt   ┆ 0       ┆ 7        ┆ 86    ┆ … ┆ 66      ┆ 8        ┆ 14       ┆ 411       │
│ bassvictim   ┆ 5       ┆ 90       ┆ 35    ┆ … ┆ 65      ┆ 73       ┆ 26       ┆ 369       │
│ astrid sonne ┆ 4       ┆ 2        ┆ 36    ┆ … ┆ 9       ┆ 8        ┆ 4        ┆ 301       │
│ vegyn        ┆ 5       ┆ 6        ┆ 2     ┆ … ┆ 10      ┆ 11       ┆ 4        ┆ 301       │
│ …            ┆ …       ┆ …        ┆ …     ┆ … ┆ …       ┆ …        ┆ …        ┆ …         │
│ mj lenderman ┆ 0       ┆ 6        ┆ 129   ┆ … ┆ 5       ┆ 1        ┆ 4        ┆ 174       │
│ jane remover ┆ 36      ┆ 22       ┆ 17    ┆ … ┆ 0       ┆ 3        ┆ 2        ┆ 167       │
│ blood orange ┆ 0       ┆ 0        ┆ 0     ┆ … ┆ 4       ┆ 3        ┆ 10       ┆ 166       │
│ 1tbsp        ┆ 10      ┆ 31       ┆ 5     ┆ … ┆ 1       ┆ 2        ┆ 1        ┆ 159       │
│ 2hollis      ┆ 26      ┆ 13       ┆ 9     ┆ … ┆ 1       ┆ 1        ┆ 1        ┆ 159       │
└──────────────┴─────────┴──────────┴───────┴───┴─────────┴──────────┴──────────┴───────────┘

## "Throwback" plays — replaying old favorites after a long gap

In [ ]:
# # Cumulative listening per track, so each record gets a number representing the n'th time of listening to a track.
# bv = (
#     df.sort(pl.col("date_played_unix"), descending=False)
#     .filter(pl.col("track_played_utc").dt.year() == year)
#     .filter(pl.col("artist_name") == "bassvictim")
#     .filter(pl.col("track_name").len().over("track_name") > 10)
#     .with_columns(
#         track_nth_scrobble = pl.col("track_name").cum_count().over(pl.col("track_name"))
#     )
# )
# bv.head()

In [47]:
(
    df
    .sort(pl.col("track_played_utc"), descending=False)
    .with_columns(
        last_played_delta = (
            pl.col("track_played_utc") - pl.col("track_played_utc").shift(1).over("track_name")
            ).dt.total_days(fractional=True).fill_null(0).ceil()
    )
).filter(pl.col("artist_name") == "bladee")

shape: (4_356, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ artist_na ┆ artist_mb ┆ album_nam ┆ album_mbi ┆ … ┆ track_mbi ┆ date_play ┆ track_pla ┆ last_pla │
│ me        ┆ id        ┆ e         ┆ d         ┆   ┆ d         ┆ ed_unix   ┆ yed_utc   ┆ yed_delt │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ a        │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ i64       ┆ datetime[ ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ μs]       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ bladee    ┆ cd689e77- ┆ drama     ┆           ┆ … ┆           ┆ 162149411 ┆ 2021-05-2 ┆ 0.0      │
│           ┆ dfdd-4f81 ┆ (feat.    ┆           ┆   ┆           ┆ 4         ┆ 0         ┆          │
│           ┆ -b50c-5e5 ┆ charli    ┆           ┆   ┆           ┆           ┆ 07:01:54  ┆          │
│           ┆ a3f…      ┆ xcx)      ┆           ┆   ┆           ┆           ┆           ┆          │
│ bladee    ┆ cd689e77- ┆ gluee     ┆ 250bafde- ┆ … ┆           ┆ 162149449 ┆ 2021-05-2 ┆ 0.0      │
│           ┆ dfdd-4f81 ┆           ┆ fd0c-4490 ┆   ┆           ┆ 5         ┆ 0         ┆          │
│           ┆ -b50c-5e5 ┆           ┆ -a728-5f7 ┆   ┆           ┆           ┆ 07:08:15  ┆          │
│           ┆ a3f…      ┆           ┆ 41f…      ┆   ┆           ┆           ┆           ┆          │
│ bladee    ┆ cd689e77- ┆ working   ┆ 587b563c- ┆ … ┆ 22de2b38- ┆ 162149464 ┆ 2021-05-2 ┆ 0.0      │
│           ┆ dfdd-4f81 ┆ on dying  ┆ 73ff-4d81 ┆   ┆ a027-49fe ┆ 4         ┆ 0         ┆          │
│           ┆ -b50c-5e5 ┆           ┆ -b669-b49 ┆   ┆ -8e99-c30 ┆           ┆ 07:10:44  ┆          │
│           ┆ a3f…      ┆           ┆ a2e…      ┆   ┆ 809…      ┆           ┆           ┆          │
│ bladee    ┆ cd689e77- ┆ red light ┆ 725f97cb- ┆ … ┆ 404d136c- ┆ 162149477 ┆ 2021-05-2 ┆ 0.0      │
│           ┆ dfdd-4f81 ┆           ┆ 5e7a-4bbb ┆   ┆ 174c-4cb5 ┆ 2         ┆ 0         ┆          │
│           ┆ -b50c-5e5 ┆           ┆ -be43-c65 ┆   ┆ -9fb0-1e8 ┆           ┆ 07:12:52  ┆          │
│           ┆ a3f…      ┆           ┆ 004…      ┆   ┆ 859…      ┆           ┆           ┆          │
│ bladee    ┆ cd689e77- ┆ working   ┆ 587b563c- ┆ … ┆ 22de2b38- ┆ 162149893 ┆ 2021-05-2 ┆ 1.0      │
│           ┆ dfdd-4f81 ┆ on dying  ┆ 73ff-4d81 ┆   ┆ a027-49fe ┆ 2         ┆ 0         ┆          │
│           ┆ -b50c-5e5 ┆           ┆ -b669-b49 ┆   ┆ -8e99-c30 ┆           ┆ 08:22:12  ┆          │
│           ┆ a3f…      ┆           ┆ a2e…      ┆   ┆ 809…      ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ bladee    ┆ cd689e77- ┆ love is a ┆ 3540f010- ┆ … ┆ 6253d641- ┆ 177428368 ┆ 2026-03-2 ┆ 0.0      │
│           ┆ dfdd-4f81 ┆ state     ┆ 4c99-4c9e ┆   ┆ 5088-4908 ┆ 7         ┆ 3         ┆          │
│           ┆ -b50c-5e5 ┆           ┆ -80e1-3db ┆   ┆ -96df-100 ┆           ┆ 16:34:47  ┆          │
│           ┆ a3f…      ┆           ┆ a8f…      ┆   ┆ b4e…      ┆           ┆           ┆          │
│ bladee    ┆ cd689e77- ┆ eversince ┆ 96e5ccf7- ┆ … ┆ ecd0d043- ┆ 177428391 ┆ 2026-03-2 ┆ 517.0    │
│           ┆ dfdd-4f81 ┆           ┆ 2ba9-4f94 ┆   ┆ fa8e-44e1 ┆ 4         ┆ 3         ┆          │
│           ┆ -b50c-5e5 ┆           ┆ -944d-79c ┆   ┆ -926b-94e ┆           ┆ 16:38:34  ┆          │
│           ┆ a3f…      ┆           ┆ a01…      ┆   ┆ 108…      ┆           ┆           ┆          │
│ bladee    ┆ cd689e77- ┆ sesame    ┆ 2c0a269b- ┆ … ┆ 1907b9ad- ┆ 177435599 ┆ 2026-03-2 ┆ 26.0     │
│           ┆ dfdd-4f81 ┆ street    ┆ 535a-47fe ┆   ┆ 2964-4889 ┆ 5         ┆ 4         ┆          │
│           ┆ -b50c-5e5 ┆           ┆ -97b2-fa4 ┆   ┆ -9df3-be4 ┆           ┆ 12:39:55  ┆          │
│           ┆ a3f…      ┆           ┆ d65…      ┆   ┆ 4ae…      ┆           ┆           ┆          │
│ bladee    ┆ cd689e77- ┆ eversince ┆ 96e5ccf7- ┆ … ┆ 1cb62976- ┆ 177436071 ┆ 2026-03-2 ┆ 19.0     │
│           ┆ dfdd-4f81 ┆           ┆ 2ba9-4f94 ┆   ┆ c4a5-4fd5 ┆ 0         ┆ 4         ┆          │
│           ┆ -b50c-5e5 ┆           ┆ -944d-79c ┆   ┆ -8319-20e ┆           ┆ 13:58:30  ┆          │
│           ┆ a3f…      ┆           ┆ a01…      ┆   ┆ 653…      ┆           ┆           ┆          │
│ bladee    ┆ cd689e77- ┆ love is a ┆ 3540f010- ┆ … ┆ 84dfc956- ┆ 177444911 ┆ 2026-03-2 ┆ 2.0      │
│           ┆ dfdd-4f81 ┆ state     ┆ 4c99-4c9e ┆   ┆ 1fe4-4f67 ┆ 8         ┆ 5         ┆          │
│           ┆ -b50c-5e5 ┆           ┆ -80e1-3db ┆   ┆ -a846-bee ┆           ┆ 14:31:58  ┆          │
│           ┆ a3f…      ┆           ┆ a8f…      ┆   ┆ a7c…      ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘