In [14]:
import duckdb
import polars as pl
import pendulum
from pathlib import Path

data_dir = Path("../data/lastfm/listening")
db = duckdb.read_json(data_dir/"*.jsonl")
df = db.pl()

df = df.with_columns(
    pl.from_epoch(
        pl.col("date_played_unix"), time_unit="s"
    ).alias("track_played_utc")
)
print("Raw data:", df.shape)

df = df.unique("date_played_unix") # Not so exact with which duplicate gets removed
print("Duplicate timestamps removed:", df.unique("date_played_unix").shape)

Raw data: (110513, 8)
Duplicate timestamps removed: (108066, 8)

In [15]:
( 
    df
    .sort(pl.col("date_played_unix"), descending=False) 
    .filter(pl.col("track_played_utc").dt.year() == 2025)
    .with_columns(
        played_delta_s = pl.col("date_played_unix").diff().fill_null(0)
    ).filter(pl.col("date_played_unix") <= 1741521825)
).sort(pl.col("date_played_unix"), descending=True).head(2)

shape: (2, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ artist_na ┆ artist_mb ┆ album_nam ┆ album_mbi ┆ … ┆ track_mbi ┆ date_play ┆ track_pla ┆ played_d │
│ me        ┆ id        ┆ e         ┆ d         ┆   ┆ d         ┆ ed_unix   ┆ yed_utc   ┆ elta_s   │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ i64       ┆ datetime[ ┆ i64      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ μs]       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Dean      ┆ e8bd5b47- ┆ Black     ┆ 128051d5- ┆ … ┆ 99bb312d- ┆ 174152182 ┆ 2025-03-0 ┆ 149      │
│ Blunt     ┆ e8b4-4671 ┆ Metal 2   ┆ 20f6-4abe ┆   ┆ 1521-4603 ┆ 5         ┆ 9         ┆          │
│           ┆ -a9f6-590 ┆           ┆ -a30e-661 ┆   ┆ -8b60-a95 ┆           ┆ 12:03:45  ┆          │
│           ┆ a92…      ┆           ┆ cf5…      ┆   ┆ 80f…      ┆           ┆           ┆          │
│ Dean      ┆           ┆ BLACK     ┆           ┆ … ┆           ┆ 174152167 ┆ 2025-03-0 ┆ 283      │
│ Blunt     ┆           ┆ METAL 2   ┆           ┆   ┆           ┆ 6         ┆ 9         ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 12:01:16  ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

Loading data from Spotify exported streaming history

In [16]:
df.columns

['artist_name',
 'artist_mbid',
 'album_name',
 'album_mbid',
 'track_name',
 'track_mbid',
 'date_played_unix',
 'track_played_utc']

In [17]:
from pathlib import Path
spotify_dir = Path("../data/spotify")
spotify_db = duckdb.read_json(spotify_dir/"*.json")
spotify_df = spotify_db.pl()
spotify_df.head()

shape: (5, 23)
┌────────────┬──────────┬───────────┬────────────┬───┬─────────┬─────────┬────────────┬────────────┐
│ ts         ┆ platform ┆ ms_played ┆ conn_count ┆ … ┆ skipped ┆ offline ┆ offline_ti ┆ incognito_ │
│ ---        ┆ ---      ┆ ---       ┆ ry         ┆   ┆ ---     ┆ ---     ┆ mestamp    ┆ mode       │
│ datetime[μ ┆ str      ┆ i64       ┆ ---        ┆   ┆ bool    ┆ bool    ┆ ---        ┆ ---        │
│ s]         ┆          ┆           ┆ str        ┆   ┆         ┆         ┆ i64        ┆ bool       │
╞════════════╪══════════╪═══════════╪════════════╪═══╪═════════╪═════════╪════════════╪════════════╡
│ 2024-11-17 ┆ osx      ┆ 150092    ┆ NO         ┆ … ┆ true    ┆ false   ┆ 1731858566 ┆ false      │
│ 15:51:57   ┆          ┆           ┆            ┆   ┆         ┆         ┆            ┆            │
│ 2024-11-17 ┆ osx      ┆ 104506    ┆ NO         ┆ … ┆ false   ┆ false   ┆ 1731858718 ┆ false      │
│ 15:53:42   ┆          ┆           ┆            ┆   ┆         ┆         ┆            ┆            │
│ 2024-11-17 ┆ osx      ┆ 139586    ┆ NO         ┆ … ┆ false   ┆ false   ┆ 1731858822 ┆ false      │
│ 15:56:02   ┆          ┆           ┆            ┆   ┆         ┆         ┆            ┆            │
│ 2024-11-17 ┆ osx      ┆ 155406    ┆ NO         ┆ … ┆ true    ┆ false   ┆ 1731858962 ┆ false      │
│ 15:58:39   ┆          ┆           ┆            ┆   ┆         ┆         ┆            ┆            │
│ 2024-11-17 ┆ osx      ┆ 50677     ┆ NO         ┆ … ┆ true    ┆ false   ┆ 1731859119 ┆ false      │
│ 15:59:31   ┆          ┆           ┆            ┆   ┆         ┆         ┆            ┆            │
└────────────┴──────────┴───────────┴────────────┴───┴─────────┴─────────┴────────────┴────────────┘

In [18]:
new_col_names = {
    'ts': "track_played_utc",
    'master_metadata_track_name': "track_name",
    'master_metadata_album_artist_name': "artist_name",
    'master_metadata_album_album_name': "album_name",
    'offline_timestamp': "date_played_unix",
}
spotify_df = spotify_df.select(
    [
        'ts',
        'ms_played',
        'master_metadata_track_name',
        'master_metadata_album_artist_name',
        'master_metadata_album_album_name',
        'offline_timestamp',
        # 'skipped',
    ]
).rename(new_col_names)
spotify_df

shape: (32_216, 6)
┌─────────────────┬───────────┬─────────────────┬────────────────┬────────────────┬────────────────┐
│ track_played_ut ┆ ms_played ┆ track_name      ┆ artist_name    ┆ album_name     ┆ date_played_un │
│ c               ┆ ---       ┆ ---             ┆ ---            ┆ ---            ┆ ix             │
│ ---             ┆ i64       ┆ str             ┆ str            ┆ str            ┆ ---            │
│ datetime[μs]    ┆           ┆                 ┆                ┆                ┆ i64            │
╞═════════════════╪═══════════╪═════════════════╪════════════════╪════════════════╪════════════════╡
│ 2024-11-17      ┆ 150092    ┆ Movement 9      ┆ Floating       ┆ Promises       ┆ 1731858566     │
│ 15:51:57        ┆           ┆                 ┆ Points         ┆                ┆                │
│ 2024-11-17      ┆ 104506    ┆ Michelle        ┆ Yusef Lateef   ┆ Suite 16       ┆ 1731858718     │
│ 15:53:42        ┆           ┆                 ┆                ┆                ┆                │
│ 2024-11-17      ┆ 139586    ┆ Whisky Story    ┆ Alabaster      ┆ To Cy & Lee:   ┆ 1731858822     │
│ 15:56:02        ┆           ┆ Time            ┆ DePlume        ┆ Instrumentals  ┆                │
│                 ┆           ┆                 ┆                ┆ Vol…           ┆                │
│ 2024-11-17      ┆ 155406    ┆ Electric        ┆ Steve Reich    ┆ Steve Reich:   ┆ 1731858962     │
│ 15:58:39        ┆           ┆ Counterpoint:   ┆                ┆ Electric       ┆                │
│                 ┆           ┆ II. Slo…        ┆                ┆ Counterp…      ┆                │
│ 2024-11-17      ┆ 50677     ┆ Number 2 (feat. ┆ KSI            ┆ All Over The   ┆ 1731859119     │
│ 15:59:31        ┆           ┆ Future & 21 Sa… ┆                ┆ Place          ┆                │
│ …               ┆ …         ┆ …               ┆ …              ┆ …              ┆ …              │
│ 2025-05-24      ┆ 15519     ┆ Frail           ┆ Crystal        ┆ Amnesty (I)    ┆ 1748095673     │
│ 18:03:49        ┆           ┆                 ┆ Castles        ┆                ┆                │
│ 2025-05-24      ┆ 524110    ┆ null            ┆ null           ┆ null           ┆ 1748109836     │
│ 18:12:41        ┆           ┆                 ┆                ┆                ┆                │
│ 2025-05-24      ┆ 10430     ┆ Do you wanna -  ┆ Astrid Sonne   ┆ Great Doubt    ┆ 1748110361     │
│ 18:12:51        ┆           ┆ Fine + Molina   ┆                ┆ EDITS          ┆                │
│                 ┆           ┆ E…              ┆                ┆                ┆                │
│ 2025-05-24      ┆ 2750      ┆ In My Mind      ┆ DJ Worm        ┆ In My Heart /  ┆ 1748110371     │
│ 18:12:54        ┆           ┆                 ┆                ┆ In My Mind     ┆                │
│ 2025-05-24      ┆ 323013    ┆ The Predatory   ┆ Sufjan Stevens ┆ Illinois       ┆ 1748110374     │
│ 18:18:16        ┆           ┆ Wasp of the     ┆                ┆                ┆                │
│                 ┆           ┆ Pali…           ┆                ┆                ┆                │
└─────────────────┴───────────┴─────────────────┴────────────────┴────────────────┴────────────────┘

In [19]:
spotify_df.null_count()

shape: (1, 6)
┌──────────────────┬───────────┬────────────┬─────────────┬────────────┬──────────────────┐
│ track_played_utc ┆ ms_played ┆ track_name ┆ artist_name ┆ album_name ┆ date_played_unix │
│ ---              ┆ ---       ┆ ---        ┆ ---         ┆ ---        ┆ ---              │
│ u32              ┆ u32       ┆ u32        ┆ u32         ┆ u32        ┆ u32              │
╞══════════════════╪═══════════╪════════════╪═════════════╪════════════╪══════════════════╡
│ 0                ┆ 0         ┆ 101        ┆ 101         ┆ 101        ┆ 0                │
└──────────────────┴───────────┴────────────┴─────────────┴────────────┴──────────────────┘

In [20]:
spotify_df.filter(pl.col("track_name").is_null())

shape: (101, 6)
┌─────────────────────┬───────────┬────────────┬─────────────┬────────────┬──────────────────┐
│ track_played_utc    ┆ ms_played ┆ track_name ┆ artist_name ┆ album_name ┆ date_played_unix │
│ ---                 ┆ ---       ┆ ---        ┆ ---         ┆ ---        ┆ ---              │
│ datetime[μs]        ┆ i64       ┆ str        ┆ str         ┆ str        ┆ i64              │
╞═════════════════════╪═══════════╪════════════╪═════════════╪════════════╪══════════════════╡
│ 2024-11-26 05:49:01 ┆ 170       ┆ null       ┆ null        ┆ null       ┆ 1732600140       │
│ 2025-01-22 20:09:07 ┆ 158476    ┆ null       ┆ null        ┆ null       ┆ 1737574683       │
│ 2025-01-24 16:43:07 ┆ 9287      ┆ null       ┆ null        ┆ null       ┆ 1737736977       │
│ 2025-01-29 12:13:16 ┆ 800       ┆ null       ┆ null        ┆ null       ┆ 1738152791       │
│ 2025-01-29 12:13:28 ┆ 12390     ┆ null       ┆ null        ┆ null       ┆ 1738152793       │
│ …                   ┆ …         ┆ …          ┆ …           ┆ …          ┆ …                │
│ 2025-05-24 13:20:04 ┆ 10770     ┆ null       ┆ null        ┆ null       ┆ 1748092791       │
│ 2025-05-24 13:45:06 ┆ 1499502   ┆ null       ┆ null        ┆ null       ┆ 1748092805       │
│ 2025-05-24 13:45:16 ┆ 948       ┆ null       ┆ null        ┆ null       ┆ 1748094306       │
│ 2025-05-24 14:00:21 ┆ 905038    ┆ null       ┆ null        ┆ null       ┆ 1748094316       │
│ 2025-05-24 18:12:41 ┆ 524110    ┆ null       ┆ null        ┆ null       ┆ 1748109836       │
└─────────────────────┴───────────┴────────────┴─────────────┴────────────┴──────────────────┘

Last.fm scrobble rules:
1. Track must be longer than than 30 seconds 
2. and must be played for over half of its duration or for 4 minutes (whichever occurs first)

No way to check song length unless I get the track data for every song here.

For the sake of simplicity, I'll employ Spotify's definition of a "listen", listening to a track for at least 30 seconds, to narrow down valid data entries.

In [21]:
# New scrobble rule
start_of_gap = 1738221713
end_of_gap = 1741521825
missing_data = (
    spotify_df
    .filter(
        pl.col("date_played_unix") > start_of_gap,
        pl.col("date_played_unix") < end_of_gap
    )
    .filter(
        pl.col("ms_played") >= 30000
    )
).sort(pl.col("date_played_unix"), descending=False)
missing_data

shape: (3_206, 6)
┌─────────────────┬───────────┬─────────────────┬────────────────┬────────────────┬────────────────┐
│ track_played_ut ┆ ms_played ┆ track_name      ┆ artist_name    ┆ album_name     ┆ date_played_un │
│ c               ┆ ---       ┆ ---             ┆ ---            ┆ ---            ┆ ix             │
│ ---             ┆ i64       ┆ str             ┆ str            ┆ str            ┆ ---            │
│ datetime[μs]    ┆           ┆                 ┆                ┆                ┆ i64            │
╞═════════════════╪═══════════╪═════════════════╪════════════════╪════════════════╪════════════════╡
│ 2025-01-30      ┆ 107706    ┆ Run It          ┆ clipping.      ┆ Run It         ┆ 1738221845     │
│ 07:25:54        ┆           ┆                 ┆                ┆                ┆                │
│ 2025-01-30      ┆ 123750    ┆ Seconds         ┆ Alaskan Tapes  ┆ Seconds /      ┆ 1738221981     │
│ 07:28:24        ┆           ┆                 ┆                ┆ Hólar          ┆                │
│ 2025-01-30      ┆ 126799    ┆ Suite No. 15 in ┆ George         ┆ Handel: Suites ┆ 1738222104     │
│ 07:30:36        ┆           ┆ D Minor for Ha… ┆ Frideric       ┆ For Keyboard   ┆                │
│                 ┆           ┆                 ┆ Handel         ┆                ┆                │
│ 2025-01-30      ┆ 94946     ┆ Hinoki Wood     ┆ Gia Margaret   ┆ Romantic Piano ┆ 1738222236     │
│ 07:32:11        ┆           ┆                 ┆                ┆                ┆                │
│ 2025-01-30      ┆ 80890     ┆ Staten Island   ┆ Elijah Fox     ┆ City in the    ┆ 1738222331     │
│ 07:33:33        ┆           ┆ Ferry           ┆                ┆ Sky (Piano     ┆                │
│                 ┆           ┆                 ┆                ┆ Works)         ┆                │
│ …               ┆ …         ┆ …               ┆ …              ┆ …              ┆ …              │
│ 2025-03-09      ┆ 194180    ┆ Aquamarine /    ┆ Addison Rae    ┆ Aquamarine /   ┆ 1741520700     │
│ 11:48:15        ┆           ┆ Arcamarine      ┆                ┆ Arcamarine     ┆                │
│ 2025-03-09      ┆ 268016    ┆ Motivation      ┆ Clams Casino   ┆ Instrumentals  ┆ 1741520895     │
│ 11:52:44        ┆           ┆                 ┆                ┆                ┆                │
│ 2025-03-09      ┆ 229223    ┆ Mystery or      ┆ Vegyn          ┆ Mystery or     ┆ 1741521164     │
│ 11:56:33        ┆           ┆ Misery?         ┆                ┆ Misery?        ┆                │
│ 2025-03-09      ┆ 167315    ┆ Word Vomit      ┆ DJ Suzy        ┆ Word Vomit     ┆ 1741521393     │
│ 11:59:21        ┆           ┆                 ┆                ┆                ┆                │
│ 2025-03-09      ┆ 149524    ┆ VIGIL           ┆ Dean Blunt     ┆ BLACK METAL 2  ┆ 1741521676     │
│ 12:03:45        ┆           ┆                 ┆                ┆                ┆                │
└─────────────────┴───────────┴─────────────────┴────────────────┴────────────────┴────────────────┘

In [22]:
data_out = missing_data.with_columns(
    artist_mbid = pl.lit(""),
    track_mbid = pl.lit(""),
    album_mbid = pl.lit(""),
)
data_out = data_out.select(
    [
        'artist_name',
        'artist_mbid',
        'album_name',
        'album_mbid',
        'track_name',
        'track_mbid',
        'date_played_unix',
        # 'track_played_utc'
    ]
)

In [23]:
spotify_dir = Path("../data/lastfm/listening")
data_out.write_ndjson(spotify_dir/"missing_data_jan_to_march.jsonl")

Checking artists between the two tables

In [24]:
spotify_artists = spotify_df.select("artist_name").unique()
spotify_artists.filter(pl.col("artist_name") == "Smerz")

shape: (1, 1)
┌─────────────┐
│ artist_name │
│ ---         │
│ str         │
╞═════════════╡
│ Smerz       │
└─────────────┘

In [25]:
import re

q = "fart ing ea"
re.findall(r"(^|\s)[a-z]", q)

['', ' ', ' ']

In [26]:
re.sub(r"(^|\s)[a-z]", lambda match: match.group().upper(),q)

'Fart Ing Ea'