In [1]:
import duckdb
import polars as pl
import numpy as np
import pendulum
from pathlib import Path

data_dir = Path("../data/lastfm/listening")
db = duckdb.read_json(data_dir/"*.jsonl")
df = db.pl()

df = df.with_columns(
    pl.from_epoch(
        pl.col("date_played_unix"), time_unit="s"
    ).alias("track_played_utc")
)

print("Raw data:", df.shape)

df = df.unique("date_played_unix") # Not so exact with which duplicate gets removed
print("Duplicate timestamps removed:", df.unique("date_played_unix").shape)
df = df.with_columns(
    artist_name = pl.col("artist_name").str.to_lowercase(),
    track_name = pl.col("track_name").str.to_lowercase(),
    album_name = pl.col("album_name").str.to_lowercase()
)
df.head()

Raw data: (110513, 8)
Duplicate timestamps removed: (108066, 8)

shape: (5, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ artist_nam ┆ artist_mbi ┆ album_name ┆ album_mbi ┆ track_nam ┆ track_mbi ┆ date_play ┆ track_pla │
│ e          ┆ d          ┆ ---        ┆ d         ┆ e         ┆ d         ┆ ed_unix   ┆ yed_utc   │
│ ---        ┆ ---        ┆ str        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ str        ┆            ┆ str       ┆ str       ┆ str       ┆ i64       ┆ datetime[ │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ μs]       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ alvedon    ┆            ┆ hurry up   ┆           ┆ weargue.  ┆           ┆ 173049000 ┆ 2024-11-0 │
│            ┆            ┆ mixtape    ┆           ┆           ┆           ┆ 4         ┆ 1         │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ 19:40:04  │
│ grouper    ┆ 7e571e09-8 ┆ the man    ┆ 0001130f- ┆ being her ┆ 8bcb1d02- ┆ 173195299 ┆ 2024-11-1 │
│            ┆ 87e-4544-b ┆ who died   ┆ cb3a-49b1 ┆ shadow    ┆ 89ce-4869 ┆ 5         ┆ 8         │
│            ┆ 993-eb75e7 ┆ in his     ┆ -9685-a2a ┆           ┆ -abe6-244 ┆           ┆ 18:03:15  │
│            ┆ …          ┆ boat       ┆ 734…      ┆           ┆ 9c5…      ┆           ┆           │
│ madvillain ┆ 4e024037-1 ┆ madvillain ┆ 264702af- ┆ do not    ┆           ┆ 167757301 ┆ 2023-02-2 │
│            ┆ 4b7-4aea-9 ┆ y          ┆ dd10-46b5 ┆ fire!     ┆           ┆ 5         ┆ 8         │
│            ┆ 9ad-c6ace6 ┆            ┆ -83ef-741 ┆           ┆           ┆           ┆ 08:30:15  │
│            ┆ …          ┆            ┆ 955…      ┆           ┆           ┆           ┆           │
│ clams      ┆ 772a0eb3-f ┆ instrument ┆           ┆ worth it  ┆ ef2a502c- ┆ 163473901 ┆ 2021-10-2 │
│ casino     ┆ e31-4a08-b ┆ al mixtape ┆           ┆           ┆ b4ae-46c6 ┆ 2         ┆ 0         │
│            ┆ 583-690296 ┆ 4 sampler  ┆           ┆           ┆ -bda1-4a3 ┆           ┆ 14:10:12  │
│            ┆ …          ┆            ┆           ┆           ┆ 0c7…      ┆           ┆           │
│ teen       ┆ a63a5c27-a ┆ dc snuff   ┆ 0403574e- ┆ benzo     ┆ 1091257d- ┆ 163135464 ┆ 2021-09-1 │
│ suicide    ┆ ae4-40b3-8 ┆ film /     ┆ b166-4aa1 ┆           ┆ 0aa7-44b5 ┆ 7         ┆ 1         │
│            ┆ 6c7-527496 ┆ waste      ┆ -b27e-ab4 ┆           ┆ -852a-a7f ┆           ┆ 10:04:07  │
│            ┆ …          ┆ yrself     ┆ d9c…      ┆           ┆ c00…      ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

## Your "anthem" — song played the most in a single day

In [2]:
(
    df
    .group_by(
        pl.col("track_played_utc").dt.date(), 
        pl.col("artist_name"), 
        pl.col("track_name")
    )
    .agg(
        n_daily_scrobbles = pl.len(),
    )
    .with_columns(
        rank = pl.col("n_daily_scrobbles").rank(method="ordinal", descending=True).over(
            pl.col("track_played_utc")
        )
    )
    .filter(pl.col("rank") <= 3)
).sort("track_played_utc", descending=False) # .sort("n_daily_scrobbles", descending=True)

shape: (5_207, 5)
┌──────────────────┬───────────────────────┬────────────────────────────┬───────────────────┬──────┐
│ track_played_utc ┆ artist_name           ┆ track_name                 ┆ n_daily_scrobbles ┆ rank │
│ ---              ┆ ---                   ┆ ---                        ┆ ---               ┆ ---  │
│ date             ┆ str                   ┆ str                        ┆ u32               ┆ u32  │
╞══════════════════╪═══════════════════════╪════════════════════════════╪═══════════════════╪══════╡
│ 2021-05-20       ┆ aldn                  ┆ i'm alright                ┆ 2                 ┆ 1    │
│ 2021-05-20       ┆ sematary              ┆ i'm a sinner               ┆ 2                 ┆ 2    │
│ 2021-05-20       ┆ bladee                ┆ lordship                   ┆ 2                 ┆ 3    │
│ 2021-05-21       ┆ bladee                ┆ mallwhore freeestyle       ┆ 2                 ┆ 2    │
│ 2021-05-21       ┆ shelly                ┆ steeeam                    ┆ 3                 ┆ 1    │
│ …                ┆ …                     ┆ …                          ┆ …                 ┆ …    │
│ 2026-03-24       ┆ grouper               ┆ poison tree                ┆ 2                 ┆ 2    │
│ 2026-03-24       ┆ playboi carti         ┆ lean 4 real (feat. skepta) ┆ 2                 ┆ 3    │
│ 2026-03-25       ┆ daft punk             ┆ around the world           ┆ 1                 ┆ 2    │
│ 2026-03-25       ┆ oneohtrix point never ┆ petro                      ┆ 1                 ┆ 3    │
│ 2026-03-25       ┆ hype williams         ┆ break4love                 ┆ 3                 ┆ 1    │
└──────────────────┴───────────────────────┴────────────────────────────┴───────────────────┴──────┘

## Unique artists

In [3]:
artists_2025 = (
    df
    .filter(pl.col("track_played_utc").dt.year() == 2025)
    .group_by(pl.col("artist_name"))
    .agg(
        scrobbles = pl.len()
    )
)

artists_else = (
    df
    .filter(pl.col("track_played_utc").dt.year() < 2025)
    .select(pl.col("artist_name").unique())
)

unique_artists_2025 = artists_2025.join(artists_else, "artist_name", how="anti")
unique_artists_2025.sort(pl.col("scrobbles"), descending=True)

shape: (635, 2)
┌──────────────────┬───────────┐
│ artist_name      ┆ scrobbles │
│ ---              ┆ ---       │
│ str              ┆ u32       │
╞══════════════════╪═══════════╡
│ ulla             ┆ 250       │
│ cameron winter   ┆ 152       │
│ elias rønnenfelt ┆ 135       │
│ geese            ┆ 132       │
│ emile mosseri    ┆ 112       │
│ …                ┆ …         │
│ demdike stare    ┆ 1         │
│ daniel romano    ┆ 1         │
│ dayseeker        ┆ 1         │
│ leon thomas      ┆ 1         │
│ bonkers          ┆ 1         │
└──────────────────┴───────────┘

In [4]:
def unique_artists(df, year:int=2025):

    if year == 2021:
        raise ValueError("No data before 2021 is available.")

    artists_year = (
        df
        .filter(pl.col("track_played_utc").dt.year() == year)
        .group_by(pl.col("artist_name"))
        .agg(
            scrobbles = pl.len()
        )
    )

    artists_else = (
        df
        .filter(pl.col("track_played_utc").dt.year() < year)
        .select(pl.col("artist_name").unique())
    )

    unique_artists_year = artists_year.join(artists_else, "artist_name", how="anti")
    return unique_artists_year.sort(pl.col("scrobbles"), descending=True)

In [5]:
unique_artists(df, 2025).head(10)

shape: (10, 2)
┌──────────────────┬───────────┐
│ artist_name      ┆ scrobbles │
│ ---              ┆ ---       │
│ str              ┆ u32       │
╞══════════════════╪═══════════╡
│ ulla             ┆ 250       │
│ cameron winter   ┆ 152       │
│ elias rønnenfelt ┆ 135       │
│ geese            ┆ 132       │
│ emile mosseri    ┆ 112       │
│ ragnhild og      ┆ 107       │
│ fine             ┆ 107       │
│ dj_dave          ┆ 105       │
│ snuggle          ┆ 94        │
│ fakemink         ┆ 91        │
└──────────────────┴───────────┘