# Listening habits over time

In [1]:
import duckdb
import polars as pl
from pathlib import Path

data_dir = Path("../data/lastfm/listening")
db = duckdb.read_json(data_dir/"*.jsonl")
df = db.pl()

df = df.with_columns(
    pl.from_epoch(
        pl.col("date_played_unix"), time_unit="s"
    ).alias("track_played_utc")
)

In [2]:
df.sort(pl.col("track_played_utc"), descending=True)

shape: (110_513, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ artist_nam ┆ artist_mbi ┆ album_name ┆ album_mbi ┆ track_nam ┆ track_mbi ┆ date_play ┆ track_pla │
│ e          ┆ d          ┆ ---        ┆ d         ┆ e         ┆ d         ┆ ed_unix   ┆ yed_utc   │
│ ---        ┆ ---        ┆ str        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ str        ┆            ┆ str       ┆ str       ┆ str       ┆ i64       ┆ datetime[ │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ μs]       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ Andrew     ┆ 8a0c3a4f-8 ┆ crown      ┆ 3556324c- ┆ Banner    ┆           ┆ 177446343 ┆ 2026-03-2 │
│ Aged       ┆ 115-4261-9 ┆            ┆ 7380-40b9 ┆           ┆           ┆ 2         ┆ 5         │
│            ┆ f42-30b660 ┆            ┆ -b6e6-2f1 ┆           ┆           ┆           ┆ 18:30:32  │
│            ┆ …          ┆            ┆ 722…      ┆           ┆           ┆           ┆           │
│ Lloyd      ┆ d75b3154-f ┆ Street     ┆ 55f161cd- ┆ Get It    ┆ 04f476ec- ┆ 177446266 ┆ 2026-03-2 │
│            ┆ b27-479b-b ┆ Love       ┆ e1fb-46f0 ┆ Shawty    ┆ 18e6-3003 ┆ 9         ┆ 5         │
│            ┆ 40b-b1b718 ┆            ┆ -9b2f-a26 ┆           ┆ -8b0b-5d3 ┆           ┆ 18:17:49  │
│            ┆ …          ┆            ┆ 578…      ┆           ┆ d4c…      ┆           ┆           │
│ Yeat       ┆ 9e6a6a2f-f ┆ Alivë      ┆           ┆ Diëd B4   ┆           ┆ 177446248 ┆ 2026-03-2 │
│            ┆ 696-4cc0-8 ┆            ┆           ┆           ┆           ┆ 6         ┆ 5         │
│            ┆ 7f1-e4f712 ┆            ┆           ┆           ┆           ┆           ┆ 18:14:46  │
│            ┆ …          ┆            ┆           ┆           ┆           ┆           ┆           │
│ Maya Ricci ┆            ┆ Syko       ┆           ┆ Syko      ┆           ┆ 177446236 ┆ 2026-03-2 │
│            ┆            ┆            ┆           ┆           ┆           ┆ 2         ┆ 5         │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ 18:12:42  │
│ brakence   ┆            ┆ punk2      ┆ bad4bc48- ┆ ginger    ┆ c0645055- ┆ 177446221 ┆ 2026-03-2 │
│            ┆            ┆            ┆ 356b-45fe ┆ tea       ┆ 8b90-4e90 ┆ 4         ┆ 5         │
│            ┆            ┆            ┆ -b8ad-d2b ┆           ┆ -8222-f09 ┆           ┆ 18:10:14  │
│            ┆            ┆            ┆ 897…      ┆           ┆ b80…      ┆           ┆           │
│ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         ┆ …         ┆ …         │
│ girl in    ┆ 4ae429fe-7 ┆ if i could ┆ 24255757- ┆ Did You   ┆ 61fe3879- ┆ 162149280 ┆ 2021-05-2 │
│ red        ┆ 35c-4968-8 ┆ make it go ┆ dd1e-457f ┆ Come?     ┆ 6a84-4b99 ┆ 9         ┆ 0         │
│            ┆ 253-a59142 ┆ quiet      ┆ -be06-708 ┆           ┆ -a32e-abc ┆           ┆ 06:40:09  │
│            ┆ …          ┆            ┆ c99…      ┆           ┆ 8d0…      ┆           ┆           │
│ HALA       ┆            ┆ Young      ┆           ┆ Problems  ┆           ┆ 162149261 ┆ 2021-05-2 │
│            ┆            ┆ Alumni     ┆           ┆           ┆           ┆ 8         ┆ 0         │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ 06:36:58  │
│ The Hellp  ┆ ca204bac-2 ┆ Vol. 1     ┆ a525960a- ┆ BEACON    ┆ 7f32a0b6- ┆ 162149240 ┆ 2021-05-2 │
│            ┆ 768-4d6f-a ┆            ┆ d2f1-4f63 ┆ 002       ┆ 0345-45b6 ┆ 2         ┆ 0         │
│            ┆ 5e4-8e8f90 ┆            ┆ -a9ff-002 ┆           ┆ -8a80-4c5 ┆           ┆ 06:33:22  │
│            ┆ …          ┆            ┆ c25…      ┆           ┆ 153…      ┆           ┆           │
│ Teen       ┆ a63a5c27-a ┆ i will be  ┆ 2559fbc2- ┆ dan       ┆ caa6249a- ┆ 162149210 ┆ 2021-05-2 │
│ Suicide    ┆ ae4-40b3-8 ┆ my own     ┆ 0b36-48aa ┆ collins   ┆ b66c-4c31 ┆ 4         ┆ 0         │
│            ┆ 6c7-527496 ┆ hell       ┆ -a2fd-1b3 ┆ vs. the   ┆ -8f4c-58d ┆           ┆ 06:28:24  │
│            ┆ …          ┆ because …  ┆ 6eb…      ┆ maryland  ┆ df3…      ┆           ┆           │
│            ┆            ┆            ┆           ┆ j…        ┆           ┆           ┆           │
│ Teen       ┆ a63a5c27-a ┆ i will be  ┆ 2559fbc2- ┆ cop       ┆ 469ca228- ┆ 162149193 ┆ 2021-05-2 │
│ Suicide    ┆ ae4-40b3-8 ┆ my own     ┆ 0b36-48aa ┆ graveyard ┆ fa70-4680 ┆ 5         ┆ 0         │
│            ┆ 6c7-527496 ┆ hell       ┆ -a2fd-1b3 ┆           ┆ -8782-caf ┆           ┆ 06:25:35  │
│            ┆ …          ┆ because …  ┆ 6eb…      ┆           ┆ 73b…      ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [3]:
import pendulum
last_week = pendulum.today().add(weeks=-1).naive()
jan_2026 = pendulum.datetime(2026, 1, 1).naive()

In [4]:
# Filtering monthly
df.filter(
    pl.col("track_played_utc") >= jan_2026,
    pl.col("track_played_utc") < jan_2026.add(months=1),
)

shape: (1_540, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ artist_nam ┆ artist_mbi ┆ album_name ┆ album_mbi ┆ track_nam ┆ track_mbi ┆ date_play ┆ track_pla │
│ e          ┆ d          ┆ ---        ┆ d         ┆ e         ┆ d         ┆ ed_unix   ┆ yed_utc   │
│ ---        ┆ ---        ┆ str        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ str        ┆            ┆ str       ┆ str       ┆ str       ┆ i64       ┆ datetime[ │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ μs]       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ Mark       ┆ bba25c2a-a ┆ Pleasure   ┆           ┆ Pleasure  ┆           ┆ 176989201 ┆ 2026-01-3 │
│ William    ┆ 43a-4774-9 ┆ is         ┆           ┆ Is Everyt ┆           ┆ 0         ┆ 1         │
│ Lewis      ┆ bfa-306b6c ┆ Everything ┆           ┆ hing      ┆           ┆           ┆ 20:40:10  │
│            ┆ …          ┆            ┆           ┆           ┆           ┆           ┆           │
│ Hooverphon ┆ 62dc94cc-f ┆ A New Ster ┆ 4e9ddd61- ┆ 2 Wicky   ┆ b226b9d9- ┆ 176988505 ┆ 2026-01-3 │
│ ic         ┆ 611-4345-8 ┆ eophonic   ┆ dc7f-41a2 ┆           ┆ 4d5f-461d ┆ 3         ┆ 1         │
│            ┆ 7cb-b91479 ┆ Sound      ┆ -acb2-a78 ┆           ┆ -af56-202 ┆           ┆ 18:44:13  │
│            ┆ …          ┆ Spect…     ┆ d91…      ┆           ┆ c07…      ┆           ┆           │
│ UNKLE      ┆ 6648391e-7 ┆ Psyence    ┆ 0c16fa0b- ┆ Celestial ┆ 0709c33b- ┆ 176988457 ┆ 2026-01-3 │
│            ┆ 890-4f6c-b ┆ Fiction    ┆ 7ab4-334c ┆ Annihilat ┆ f3db-3642 ┆ 1         ┆ 1         │
│            ┆ 939-976f21 ┆            ┆ -a85f-db9 ┆ ion       ┆ -83f1-ceb ┆           ┆ 18:36:11  │
│            ┆ …          ┆            ┆ 231…      ┆           ┆ 45f…      ┆           ┆           │
│ Morcheeba  ┆ 067102ea-9 ┆ Big Calm   ┆ 0c0f9ff9- ┆ Bullet    ┆ 0bb944e6- ┆ 176988431 ┆ 2026-01-3 │
│            ┆ 519-4622-9 ┆            ┆ 0b07-4d12 ┆ Proof     ┆ db8f-474d ┆ 8         ┆ 1         │
│            ┆ 077-57ca41 ┆            ┆ -8978-652 ┆           ┆ -a2e4-bd9 ┆           ┆ 18:31:58  │
│            ┆ …          ┆            ┆ 260…      ┆           ┆ 45c…      ┆           ┆           │
│ Lovage     ┆ 43e2b545-3 ┆ Nathaniel  ┆ b6313bc2- ┆ To Catch  ┆ 78a99e99- ┆ 176988412 ┆ 2026-01-3 │
│            ┆ e4a-4fd7-a ┆ Merriweath ┆ 3ec2-37be ┆ a Thief   ┆ 03e5-4416 ┆ 0         ┆ 1         │
│            ┆ 773-8daafa ┆ er         ┆ -b96b-698 ┆           ┆ -9603-e68 ┆           ┆ 18:28:40  │
│            ┆ …          ┆ present…   ┆ c03…      ┆           ┆ 2a4…      ┆           ┆           │
│ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         ┆ …         ┆ …         │
│ Dijon      ┆ cceea21d-f ┆ Baby       ┆ 7d6efc37- ┆ Rewind    ┆ 5e5338c8- ┆ 176723173 ┆ 2026-01-0 │
│            ┆ 3ec-4586-b ┆            ┆ 7513-4f3a ┆           ┆ 26d3-48d7 ┆ 8         ┆ 1         │
│            ┆ e7a-d2e939 ┆            ┆ -993f-0a3 ┆           ┆ -909b-0a4 ┆           ┆ 01:42:18  │
│            ┆ …          ┆            ┆ da9…      ┆           ┆ 2cc…      ┆           ┆           │
│ EQ         ┆            ┆ Boytoy     ┆ 2fa54bb3- ┆ Boytoy    ┆ c006770d- ┆ 176723173 ┆ 2026-01-0 │
│            ┆            ┆            ┆ c91c-4256 ┆           ┆ 6081-4fd2 ┆ 7         ┆ 1         │
│            ┆            ┆            ┆ -a485-b17 ┆           ┆ -8604-9a1 ┆           ┆ 01:42:17  │
│            ┆            ┆            ┆ 192…      ┆           ┆ c23…      ┆           ┆           │
│ Dijon      ┆ cceea21d-f ┆ Baby       ┆ 7d6efc37- ┆ Rewind    ┆ 5e5338c8- ┆ 176723158 ┆ 2026-01-0 │
│            ┆ 3ec-4586-b ┆            ┆ 7513-4f3a ┆           ┆ 26d3-48d7 ┆ 5         ┆ 1         │
│            ┆ e7a-d2e939 ┆            ┆ -993f-0a3 ┆           ┆ -909b-0a4 ┆           ┆ 01:39:45  │
│            ┆ …          ┆            ┆ da9…      ┆           ┆ 2cc…      ┆           ┆           │
│ Boys Noize ┆            ┆ LVLY       ┆           ┆ LVLY -    ┆           ┆ 176723126 ┆ 2026-01-0 │
│            ┆            ┆            ┆           ┆ MarcelDun ┆           ┆ 6         ┆ 1         │
│            ┆            ┆            ┆           ┆ e Remix   ┆           ┆           ┆ 01:34:26  │
│ VÎęzë      ┆            ┆ Papa Weg   ┆           ┆ Papa Weg  ┆           ┆ 176723107 ┆ 2026-01-0 │
│ Ãsbæk      ┆            ┆            ┆           ┆           ┆           ┆ 4         ┆ 1         │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ 01:31:14  │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [5]:
# Listening past 7 days
df.filter(
    pl.col("track_played_utc") >= pendulum.today().naive().add(weeks=-1),
    pl.col("track_played_utc") < pendulum.today().naive(),
)

shape: (169, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ artist_nam ┆ artist_mbi ┆ album_name ┆ album_mbi ┆ track_nam ┆ track_mbi ┆ date_play ┆ track_pla │
│ e          ┆ d          ┆ ---        ┆ d         ┆ e         ┆ d         ┆ ed_unix   ┆ yed_utc   │
│ ---        ┆ ---        ┆ str        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ str        ┆            ┆ str       ┆ str       ┆ str       ┆ i64       ┆ datetime[ │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ μs]       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ Andrew     ┆ 8a0c3a4f-8 ┆ crown      ┆ 3556324c- ┆ Banner    ┆           ┆ 177446343 ┆ 2026-03-2 │
│ Aged       ┆ 115-4261-9 ┆            ┆ 7380-40b9 ┆           ┆           ┆ 2         ┆ 5         │
│            ┆ f42-30b660 ┆            ┆ -b6e6-2f1 ┆           ┆           ┆           ┆ 18:30:32  │
│            ┆ …          ┆            ┆ 722…      ┆           ┆           ┆           ┆           │
│ Lloyd      ┆ d75b3154-f ┆ Street     ┆ 55f161cd- ┆ Get It    ┆ 04f476ec- ┆ 177446266 ┆ 2026-03-2 │
│            ┆ b27-479b-b ┆ Love       ┆ e1fb-46f0 ┆ Shawty    ┆ 18e6-3003 ┆ 9         ┆ 5         │
│            ┆ 40b-b1b718 ┆            ┆ -9b2f-a26 ┆           ┆ -8b0b-5d3 ┆           ┆ 18:17:49  │
│            ┆ …          ┆            ┆ 578…      ┆           ┆ d4c…      ┆           ┆           │
│ Yeat       ┆ 9e6a6a2f-f ┆ Alivë      ┆           ┆ Diëd B4   ┆           ┆ 177446248 ┆ 2026-03-2 │
│            ┆ 696-4cc0-8 ┆            ┆           ┆           ┆           ┆ 6         ┆ 5         │
│            ┆ 7f1-e4f712 ┆            ┆           ┆           ┆           ┆           ┆ 18:14:46  │
│            ┆ …          ┆            ┆           ┆           ┆           ┆           ┆           │
│ Maya Ricci ┆            ┆ Syko       ┆           ┆ Syko      ┆           ┆ 177446236 ┆ 2026-03-2 │
│            ┆            ┆            ┆           ┆           ┆           ┆ 2         ┆ 5         │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ 18:12:42  │
│ brakence   ┆            ┆ punk2      ┆ bad4bc48- ┆ ginger    ┆ c0645055- ┆ 177446221 ┆ 2026-03-2 │
│            ┆            ┆            ┆ 356b-45fe ┆ tea       ┆ 8b90-4e90 ┆ 4         ┆ 5         │
│            ┆            ┆            ┆ -b8ad-d2b ┆           ┆ -8222-f09 ┆           ┆ 18:10:14  │
│            ┆            ┆            ┆ 897…      ┆           ┆ b80…      ┆           ┆           │
│ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         ┆ …         ┆ …         │
│ Imagine    ┆            ┆ Stain      ┆ 09943b47- ┆ Cementeri ┆ a60a46e4- ┆ 177425261 ┆ 2026-03-2 │
│ Drowning   ┆            ┆ Licker     ┆ e53f-4e83 ┆ o         ┆ f0a1-4bcf ┆ 6         ┆ 3         │
│            ┆            ┆            ┆ -a634-aa3 ┆           ┆ -b2ff-aa5 ┆           ┆ 07:56:56  │
│            ┆            ┆            ┆ b9c…      ┆           ┆ a27…      ┆           ┆           │
│ Imagine    ┆            ┆ Stain      ┆ 09943b47- ┆ Peroxide  ┆           ┆ 177425230 ┆ 2026-03-2 │
│ Drowning   ┆            ┆ Licker     ┆ e53f-4e83 ┆           ┆           ┆ 2         ┆ 3         │
│            ┆            ┆            ┆ -a634-aa3 ┆           ┆           ┆           ┆ 07:51:42  │
│            ┆            ┆            ┆ b9c…      ┆           ┆           ┆           ┆           │
│ Imagine    ┆            ┆ Stain      ┆ 09943b47- ┆ Canada    ┆ a38fe6b9- ┆ 177425221 ┆ 2026-03-2 │
│ Drowning   ┆            ┆ Licker     ┆ e53f-4e83 ┆           ┆ f5fd-49b6 ┆ 6         ┆ 3         │
│            ┆            ┆            ┆ -a634-aa3 ┆           ┆ -b3af-4d9 ┆           ┆ 07:50:16  │
│            ┆            ┆            ┆ b9c…      ┆           ┆ 72e…      ┆           ┆           │
│ Folk Bitch ┆ 41f03c6d-5 ┆ Now Would  ┆ 1d8382c0- ┆ God's A   ┆ 0ce1fd31- ┆ 177425218 ┆ 2026-03-2 │
│ Trio       ┆ 6e1-428a-a ┆ Be A Good  ┆ c1cb-46f5 ┆ Different ┆ 348d-42a3 ┆ 7         ┆ 3         │
│            ┆ 186-9e81e5 ┆ Time       ┆ -a3bf-81b ┆ Sword     ┆ -92ea-a37 ┆           ┆ 07:49:47  │
│            ┆ …          ┆            ┆ b9f…      ┆           ┆ d2f…      ┆           ┆           │
│ Against    ┆ c8e6242c-b ┆ Issue #9   ┆           ┆ LKJ       ┆           ┆ 177424947 ┆ 2026-03-2 │
│ All Logic  ┆ c88-446c-8 ┆            ┆           ┆           ┆           ┆ 1         ┆ 3         │
│            ┆ 723-e354b8 ┆            ┆           ┆           ┆           ┆           ┆ 07:04:31  │
│            ┆ …          ┆            ┆           ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [6]:
# Filtering daily
df.filter(
    pl.col("track_played_utc") >= last_week,
    pl.col("track_played_utc") < last_week.add(days=1),
)

shape: (85, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ artist_nam ┆ artist_mbi ┆ album_name ┆ album_mbi ┆ track_nam ┆ track_mbi ┆ date_play ┆ track_pla │
│ e          ┆ d          ┆ ---        ┆ d         ┆ e         ┆ d         ┆ ed_unix   ┆ yed_utc   │
│ ---        ┆ ---        ┆ str        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ str        ┆            ┆ str       ┆ str       ┆ str       ┆ i64       ┆ datetime[ │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ μs]       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ LOVING     ┆ d8a1bce4-2 ┆ Any Light  ┆ 7b842b31- ┆ Any Light ┆ 0bf8a748- ┆ 177429069 ┆ 2026-03-2 │
│            ┆ 126-4758-9 ┆            ┆ eca0-4877 ┆           ┆ 2d0b-4b2a ┆ 8         ┆ 3         │
│            ┆ f70-bd992f ┆            ┆ -a05a-67c ┆           ┆ -8676-356 ┆           ┆ 18:31:38  │
│            ┆ …          ┆            ┆ fc5…      ┆           ┆ 2fc…      ┆           ┆           │
│ meat       ┆ 0943f55d-1 ┆ leave this ┆           ┆ leave     ┆           ┆ 177429022 ┆ 2026-03-2 │
│ computer   ┆ c10-4a52-a ┆ world      ┆           ┆ this      ┆           ┆ 6         ┆ 3         │
│            ┆ 1ef-06e625 ┆ behind     ┆           ┆ world     ┆           ┆           ┆ 18:23:46  │
│            ┆ …          ┆            ┆           ┆ behind    ┆           ┆           ┆           │
│ Underworld ┆ ba2f4f3b-0 ┆ A Hundred  ┆ 2a08fd66- ┆ Two       ┆ 56f809aa- ┆ 177428976 ┆ 2026-03-2 │
│            ┆ 293-4bc8-b ┆ Days Off   ┆ 78f1-4366 ┆ Months    ┆ 6ed7-43c1 ┆ 1         ┆ 3         │
│            ┆ b94-2f73b5 ┆            ┆ -87a7-fd7 ┆ Off       ┆ -8c98-e01 ┆           ┆ 18:16:01  │
│            ┆ …          ┆            ┆ 6a4…      ┆           ┆ f7b…      ┆           ┆           │
│ Chris      ┆ 5b7f4511-1 ┆ Darkness   ┆ 56464592- ┆ Darkness  ┆           ┆ 177428957 ┆ 2026-03-2 │
│ Stussy     ┆ 764-4d80-8 ┆            ┆ 69b9-4ceb ┆           ┆           ┆ 1         ┆ 3         │
│            ┆ 3b5-8c150f ┆            ┆ -8b58-705 ┆           ┆           ┆           ┆ 18:12:51  │
│            ┆ …          ┆            ┆ e18…      ┆           ┆           ┆           ┆           │
│ Milky      ┆            ┆ Just The   ┆ 5fbcffac- ┆ Just The  ┆ a23cf145- ┆ 177428942 ┆ 2026-03-2 │
│            ┆            ┆ Way You    ┆ ec9d-4211 ┆ Way You   ┆ 4853-3763 ┆ 1         ┆ 3         │
│            ┆            ┆ Are        ┆ -9c78-51b ┆ Are       ┆ -aed6-568 ┆           ┆ 18:10:21  │
│            ┆            ┆            ┆ 97d…      ┆           ┆ 51e…      ┆           ┆           │
│ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         ┆ …         ┆ …         │
│ Imagine    ┆            ┆ Stain      ┆ 09943b47- ┆ Cementeri ┆ a60a46e4- ┆ 177425261 ┆ 2026-03-2 │
│ Drowning   ┆            ┆ Licker     ┆ e53f-4e83 ┆ o         ┆ f0a1-4bcf ┆ 6         ┆ 3         │
│            ┆            ┆            ┆ -a634-aa3 ┆           ┆ -b2ff-aa5 ┆           ┆ 07:56:56  │
│            ┆            ┆            ┆ b9c…      ┆           ┆ a27…      ┆           ┆           │
│ Imagine    ┆            ┆ Stain      ┆ 09943b47- ┆ Peroxide  ┆           ┆ 177425230 ┆ 2026-03-2 │
│ Drowning   ┆            ┆ Licker     ┆ e53f-4e83 ┆           ┆           ┆ 2         ┆ 3         │
│            ┆            ┆            ┆ -a634-aa3 ┆           ┆           ┆           ┆ 07:51:42  │
│            ┆            ┆            ┆ b9c…      ┆           ┆           ┆           ┆           │
│ Imagine    ┆            ┆ Stain      ┆ 09943b47- ┆ Canada    ┆ a38fe6b9- ┆ 177425221 ┆ 2026-03-2 │
│ Drowning   ┆            ┆ Licker     ┆ e53f-4e83 ┆           ┆ f5fd-49b6 ┆ 6         ┆ 3         │
│            ┆            ┆            ┆ -a634-aa3 ┆           ┆ -b3af-4d9 ┆           ┆ 07:50:16  │
│            ┆            ┆            ┆ b9c…      ┆           ┆ 72e…      ┆           ┆           │
│ Folk Bitch ┆ 41f03c6d-5 ┆ Now Would  ┆ 1d8382c0- ┆ God's A   ┆ 0ce1fd31- ┆ 177425218 ┆ 2026-03-2 │
│ Trio       ┆ 6e1-428a-a ┆ Be A Good  ┆ c1cb-46f5 ┆ Different ┆ 348d-42a3 ┆ 7         ┆ 3         │
│            ┆ 186-9e81e5 ┆ Time       ┆ -a3bf-81b ┆ Sword     ┆ -92ea-a37 ┆           ┆ 07:49:47  │
│            ┆ …          ┆            ┆ b9f…      ┆           ┆ d2f…      ┆           ┆           │
│ Against    ┆ c8e6242c-b ┆ Issue #9   ┆           ┆ LKJ       ┆           ┆ 177424947 ┆ 2026-03-2 │
│ All Logic  ┆ c88-446c-8 ┆            ┆           ┆           ┆           ┆ 1         ┆ 3         │
│            ┆ 723-e354b8 ┆            ┆           ┆           ┆           ┆           ┆ 07:04:31  │
│            ┆ …          ┆            ┆           ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

## Listening streaks

In [7]:
df_2025 = df.filter(
    pl.col("track_played_utc") >= pendulum.datetime(2025, 1, 1).naive(),
    pl.col("track_played_utc") < pendulum.datetime(2026, 1, 1).naive()
)

In [8]:
dates_2025 = df_2025.select(
    pl.col("track_played_utc").dt.date().unique().alias("date")
)

listening_streak_2025 = dates_2025.with_columns(
    is_break = pl.col("date").diff() != pl.duration(days=1)
).with_columns(
    streak_id = pl.col("is_break").fill_null(True).cum_sum()
)

streak_counts_2025 = (
    listening_streak_2025
    .group_by(pl.col("streak_id"))
    .agg(
        start_date = pl.col("date").min(),
        end_date = pl.col("date").max(),
        streak_length = pl.len()
    )
)
streak_counts_2025

shape: (3, 4)
┌───────────┬────────────┬────────────┬───────────────┐
│ streak_id ┆ start_date ┆ end_date   ┆ streak_length │
│ ---       ┆ ---        ┆ ---        ┆ ---           │
│ u32       ┆ date       ┆ date       ┆ u32           │
╞═══════════╪════════════╪════════════╪═══════════════╡
│ 2         ┆ 2025-01-03 ┆ 2025-08-02 ┆ 212           │
│ 1         ┆ 2025-01-01 ┆ 2025-01-01 ┆ 1             │
│ 3         ┆ 2025-08-04 ┆ 2025-12-31 ┆ 150           │
└───────────┴────────────┴────────────┴───────────────┘

In [9]:
def listening_streak(df:pl.DataFrame, year:int=2025):
    df = df.filter(
        pl.col("track_played_utc") >= pendulum.datetime(year, 1, 1).naive(),
        pl.col("track_played_utc") < pendulum.datetime(year+1, 1, 1).naive()
    )

    dates = df.select(
        pl.col("track_played_utc").dt.date().unique().alias("date")
    )

    listening_streak = dates.with_columns(
        is_break = pl.col("date").diff() != pl.duration(days=1) 
    ).with_columns( 
        streak_id = pl.col("is_break").fill_null(True).cum_sum()
    )

    streak_stats = (
        listening_streak
        .group_by(pl.col("streak_id"))
        .agg(
            start_date = pl.col("date").min(),
            end_date = pl.col("date").max(),
            streak_length = pl.len()
        )
    )
    streak_stats = streak_stats.sort(pl.col("streak_length"), descending=True)

    return streak_stats

In [10]:
listening_streak(df=df, year=2021)

shape: (5, 4)
┌───────────┬────────────┬────────────┬───────────────┐
│ streak_id ┆ start_date ┆ end_date   ┆ streak_length │
│ ---       ┆ ---        ┆ ---        ┆ ---           │
│ u32       ┆ date       ┆ date       ┆ u32           │
╞═══════════╪════════════╪════════════╪═══════════════╡
│ 5         ┆ 2021-09-29 ┆ 2021-12-31 ┆ 94            │
│ 2         ┆ 2021-06-22 ┆ 2021-07-26 ┆ 35            │
│ 4         ┆ 2021-08-27 ┆ 2021-09-27 ┆ 32            │
│ 1         ┆ 2021-05-20 ┆ 2021-06-20 ┆ 32            │
│ 3         ┆ 2021-07-28 ┆ 2021-08-25 ┆ 29            │
└───────────┴────────────┴────────────┴───────────────┘

## Year-over-year listening trends

In [11]:
tot_scrobbles_25 = df_2025.group_by(pl.col("track_played_utc").dt.date()).agg(total_scrobbles = pl.len())
tot_scrobbles_25 = tot_scrobbles_25.sort("track_played_utc", descending=True)

In [12]:
import plotly.express as px
px.line(tot_scrobbles_25, "track_played_utc", "total_scrobbles")

In [13]:
from scipy.signal import savgol_filter
total_scrobbles = tot_scrobbles_25.select(pl.col("total_scrobbles")).to_numpy().flatten()
tot_scrobbles_25 = tot_scrobbles_25.with_columns(filtered_scrobbles = savgol_filter(total_scrobbles, window_length=28, polyorder=3, axis=0))
tot_scrobbles_25

shape: (363, 3)
┌──────────────────┬─────────────────┬────────────────────┐
│ track_played_utc ┆ total_scrobbles ┆ filtered_scrobbles │
│ ---              ┆ ---             ┆ ---                │
│ date             ┆ u32             ┆ f64                │
╞══════════════════╪═════════════════╪════════════════════╡
│ 2025-12-31       ┆ 35              ┆ 27.058319          │
│ 2025-12-30       ┆ 27              ┆ 24.596712          │
│ 2025-12-29       ┆ 22              ┆ 22.760696          │
│ 2025-12-28       ┆ 22              ┆ 21.499448          │
│ 2025-12-27       ┆ 4               ┆ 20.762145          │
│ …                ┆ …               ┆ …                  │
│ 2025-01-06       ┆ 91              ┆ 69.001278          │
│ 2025-01-05       ┆ 113             ┆ 60.783115          │
│ 2025-01-04       ┆ 56              ┆ 50.96065           │
│ 2025-01-03       ┆ 11              ┆ 39.416124          │
│ 2025-01-01       ┆ 7               ┆ 26.031781          │
└──────────────────┴─────────────────┴────────────────────┘

In [14]:
import plotly.express as px
px.line(tot_scrobbles_25, "track_played_utc", [ "total_scrobbles", "filtered_scrobbles" ], title="2025")

Comment: Do something similar with artists?

## Most active listening hours of the day and days of the week

In [15]:
df_2025 = df.filter(
    pl.col("track_played_utc") >= pendulum.datetime(2025, 1, 1).naive(),
    pl.col("track_played_utc") < pendulum.datetime(2026, 1, 1).naive()
)

In [16]:
# peak hours (keep in mind hours in UTC, so +1h for actual timeslot)
(df_2025
    .group_by(pl.col("track_played_utc").dt.hour())
    .agg(scrobbles_by_hour = pl.len())
).sort("scrobbles_by_hour", descending=True)

shape: (24, 2)
┌──────────────────┬───────────────────┐
│ track_played_utc ┆ scrobbles_by_hour │
│ ---              ┆ ---               │
│ i8               ┆ u32               │
╞══════════════════╪═══════════════════╡
│ 9                ┆ 1991              │
│ 11               ┆ 1864              │
│ 10               ┆ 1850              │
│ 8                ┆ 1814              │
│ 13               ┆ 1789              │
│ …                ┆ …                 │
│ 0                ┆ 59                │
│ 1                ┆ 27                │
│ 2                ┆ 8                 │
│ 4                ┆ 5                 │
│ 3                ┆ 4                 │
└──────────────────┴───────────────────┘

In [17]:
# peak days of the week
weekdays = {1: "Monday", 2: "Tuesday", 3: "Wednesday", 4: "Thursday",
            5: "Friday", 6: "Saturday", 7: "Sunday"}
(df_2025
    .group_by(pl.col("track_played_utc").dt.weekday().alias("weekday_idx"))
    .agg(scrobbles_by_weekday = pl.len())
    .sort("scrobbles_by_weekday", descending=True)
    .with_columns(weekday = pl.col("weekday_idx").replace(weekdays, default=None).alias("weekday"))
)

/var/folders/3z/fbv_cnz175v2v_9cqnh_3t5r0000gn/T/ipykernel_11265/3680256808.py:8: DeprecationWarning: the `default` parameter for `replace` is deprecated. Use `replace_strict` instead to set a default while replacing values.
(Deprecated in version 1.0.0)
  .with_columns(weekday = pl.col("weekday_idx").replace(weekdays, default=None).alias("weekday"))

shape: (7, 3)
┌─────────────┬──────────────────────┬───────────┐
│ weekday_idx ┆ scrobbles_by_weekday ┆ weekday   │
│ ---         ┆ ---                  ┆ ---       │
│ i8          ┆ u32                  ┆ str       │
╞═════════════╪══════════════════════╪═══════════╡
│ 5           ┆ 3723                 ┆ Friday    │
│ 1           ┆ 3544                 ┆ Monday    │
│ 4           ┆ 3464                 ┆ Thursday  │
│ 3           ┆ 3091                 ┆ Wednesday │
│ 2           ┆ 2630                 ┆ Tuesday   │
│ 7           ┆ 1976                 ┆ Sunday    │
│ 6           ┆ 1854                 ┆ Saturday  │
└─────────────┴──────────────────────┴───────────┘