In [2]:
import requests
import tomllib
from pathlib import Path

secrets = Path("../secrets")
with open(secrets/"lastfm.toml", "rb") as f:
    lastfm_toml = tomllib.load(f)
client_id = lastfm_toml.get("lastfm-credentials").get("client_id")

In [3]:
BASE_URL = "http://ws.audioscrobbler.com/2.0/"
USER = "GammelPerson"
HEADER = {"user-agent": "GammelPerson_2025_data"}
request_parameters = {
        "api_key": client_id,
        "method": "artist.getInfo",
        "artist": "Phil Wangseyt",
        "autocorrect": 1,
        "format": "json"
    }

In [4]:
response = requests.get(url=BASE_URL, params=request_parameters, headers=HEADER)

In [5]:
if not response.raise_for_status():
    out = response.json()

out

{'error': 6,
 'message': 'The artist you supplied could not be found',
 'links': []}

In [6]:
def extract_track_data(response:dict):
    out_dict = {}
    track_data = response.get("track")

    # track info
    out_dict["track_name"] = track_data.get("name")
    out_dict["track_mbid"] = track_data.get("mbid")
    out_dict["track_duration"] = track_data.get("duration")

    out_dict["artist"] = track_data.get("artist").get("name")

    # last 
    out_dict["listeners"] = track_data.get("listeners")
    out_dict["playcount"] = track_data.get("playcount")

    album_data = track_data.get("album")
    out_dict["album_title"] = album_data.get("title")
    out_dict["album_mbid"] = album_data.get("mbid")
    out_dict["album_image_url"] = album_data.get("image")[2].get("#text")

    toptags = track_data.get("toptags").get("tag")
    out_dict["genre_tags"] = [tag.get("name") for tag in toptags] if toptags else None
    return out_dict

In [7]:
import pendulum
from math import floor
def extract_artist_data(response:dict):
    out_dict = {}
    artist_data = response.get("artist")

    out_dict["artist"] = artist_data.get("name")
    out_dict["artist_mbid"] = artist_data.get("mbid")
    
    out_dict["artist_image_url"] = artist_data.get("image")[2].get("#text")

    # last.fm stats
    out_dict["listeners"] = artist_data.get("stats").get("listeners")
    out_dict["playcount"] = artist_data.get("stats").get("playcount")

    # tags
    toptags = artist_data.get("tags").get("tag")
    out_dict["artist_genre_tags"] = [tag.get("name") for tag in toptags] if toptags else None

    # data retrieved
    out_dict["unix_timestamp"] = floor(pendulum.now(tz="UTC").timestamp())

    return out_dict

extract_artist_data(out)

AttributeError: 'NoneType' object has no attribute 'get'

In [8]:
import polars as pl
def get_track_table():
    cols = [
        "date_played_unix",
        "track_played_utc",
        "track_name",
        "artist_name",
        "track_mbid",
    ]
    lastfm_df = pl.read_parquet(
        Path("../data/lastfm/lastfm-listening-2021-2026march.parquet"),
        columns=cols
    )
    spotify_df = pl.read_parquet(
        Path("../data/spotify/2017-2021 spotify data.parquet"),
    )
    # lastfm_df = lastfm_df.with_columns(spotify_track_uri=pl.lit(""))
    # spotify_df = spotify_df.with_columns(
    #     artist_mbid=pl.lit(""), album_mbid=pl.lit(""), track_mbid=pl.lit("")
    # )
    
    # lastfm_df = lastfm_df.select(cols)
    # spotify_df = spotify_df.select(cols)

    # df = lastfm_df.vstack(spotify_df).sort(pl.col("date_played_unix"), descending=False)
    df = pl.concat([ lastfm_df, spotify_df ], how="diagonal").sort(pl.col("date_played_unix"), descending=False)
    df = ( 
        df
        .filter(pl.col("track_played_utc").dt.year() >= 2021)
        .unique(subset=["track_name"], keep="first")
        .sort("track_played_utc", descending=False)
        .drop_nulls(pl.col("track_name"))
    )

    return df

df = get_track_table()

In [11]:
df.filter(
    pl.col("track_played_utc").dt.year() == 2025,
    pl.col("track_played_utc").dt.month() == 2    
)

shape: (408, 7)
┌──────────────┬──────────────┬──────────────┬─────────────┬────────────┬────────────┬─────────────┐
│ date_played_ ┆ track_played ┆ track_name   ┆ artist_name ┆ track_mbid ┆ album_name ┆ spotify_tra │
│ unix         ┆ _utc         ┆ ---          ┆ ---         ┆ ---        ┆ ---        ┆ ck_uri      │
│ ---          ┆ ---          ┆ str          ┆ str         ┆ str        ┆ str        ┆ ---         │
│ i64          ┆ datetime[μs] ┆              ┆             ┆            ┆            ┆ str         │
╞══════════════╪══════════════╪══════════════╪═════════════╪════════════╪════════════╪═════════════╡
│ 1738433778   ┆ 2025-02-01   ┆ Grey skies   ┆ Bassvictim  ┆            ┆ null       ┆ null        │
│              ┆ 18:16:18     ┆              ┆             ┆            ┆            ┆             │
│ 1738433876   ┆ 2025-02-01   ┆ 50 /         ┆ Ngahere     ┆            ┆ null       ┆ null        │
│              ┆ 18:17:56     ┆ Everything   ┆ Wafer       ┆            ┆            ┆             │
│              ┆              ┆ Is Fine      ┆             ┆            ┆            ┆             │
│ 1738433986   ┆ 2025-02-01   ┆ Forever      ┆ Bassvictim  ┆            ┆ null       ┆ null        │
│              ┆ 18:19:46     ┆ salty        ┆             ┆            ┆            ┆             │
│ 1738434192   ┆ 2025-02-01   ┆ Life so far  ┆ Bassvictim  ┆            ┆ null       ┆ null        │
│              ┆ 18:23:12     ┆              ┆             ┆            ┆            ┆             │
│ 1738434337   ┆ 2025-02-01   ┆ I'll be      ┆ Bassvictim  ┆            ┆ null       ┆ null        │
│              ┆ 18:25:37     ┆ there        ┆             ┆            ┆            ┆             │
│ …            ┆ …            ┆ …            ┆ …           ┆ …          ┆ …          ┆ …           │
│ 1740753652   ┆ 2025-02-28   ┆ Dream        ┆ Jane        ┆            ┆ null       ┆ null        │
│              ┆ 14:40:52     ┆ Sequence     ┆ Remover     ┆            ┆            ┆             │
│ 1740762231   ┆ 2025-02-28   ┆ hot problems ┆ food house  ┆            ┆ null       ┆ null        │
│              ┆ 17:03:51     ┆              ┆             ┆            ┆            ┆             │
│ 1740764659   ┆ 2025-02-28   ┆ Digital Girl ┆ DJ Suzy     ┆            ┆ null       ┆ null        │
│              ┆ 17:44:19     ┆              ┆             ┆            ┆            ┆             │
│ 1740764987   ┆ 2025-02-28   ┆ Stay Flo     ┆ Solange     ┆            ┆ null       ┆ null        │
│              ┆ 17:49:47     ┆              ┆             ┆            ┆            ┆             │
│ 1740769436   ┆ 2025-02-28   ┆ Homie Don’t  ┆ Fcukers     ┆            ┆ null       ┆ null        │
│              ┆ 19:03:56     ┆ Shake        ┆             ┆            ┆            ┆             │
└──────────────┴──────────────┴──────────────┴─────────────┴────────────┴────────────┴─────────────┘

In [ ]:
# df.with_row_index("idx").filter(pl.col("artist_name") == "Iglooghost")

shape: (8, 6)
┌───────┬──────────────────┬───────────────────┬─────────────────┬─────────────┬───────────────────┐
│ idx   ┆ date_played_unix ┆ track_played_utc  ┆ track_name      ┆ artist_name ┆ track_mbid        │
│ ---   ┆ ---              ┆ ---               ┆ ---             ┆ ---         ┆ ---               │
│ u32   ┆ i64              ┆ datetime[μs]      ┆ str             ┆ str         ┆ str               │
╞═══════╪══════════════════╪═══════════════════╪═════════════════╪═════════════╪═══════════════════╡
│ 430   ┆ 1611730525       ┆ 2021-01-27        ┆ Amu             ┆ Iglooghost  ┆                   │
│       ┆                  ┆ 06:55:25          ┆                 ┆             ┆                   │
│ 17681 ┆ 1761054834       ┆ 2025-10-21        ┆ Blue Hum        ┆ Iglooghost  ┆ 72596ba2-974b-47d │
│       ┆                  ┆ 13:53:54          ┆                 ┆             ┆ 4-b51b-988116…    │
│ 17682 ┆ 1761054966       ┆ 2025-10-21        ┆ New Species     ┆ Iglooghost  ┆ f85163a7-e982-4eb │
│       ┆                  ┆ 13:56:06          ┆                 ┆             ┆ 6-b8e2-e633a9…    │
│ 17683 ┆ 1761064405       ┆ 2025-10-21        ┆ Alloy Flea      ┆ Iglooghost  ┆ 60791d72-ff67-4df │
│       ┆                  ┆ 16:33:25          ┆                 ┆             ┆ 3-a453-f8cfa3…    │
│ 17684 ┆ 1761079598       ┆ 2025-10-21        ┆ Spawn01 ft Cyst ┆ Iglooghost  ┆ 2e43febd-2bec-437 │
│       ┆                  ┆ 20:46:38          ┆                 ┆             ┆ f-bbe6-14f195…    │
│ 17685 ┆ 1761123638       ┆ 2025-10-22        ┆ Coral Mimic     ┆ Iglooghost  ┆ 4e08fdc9-ce2d-4e4 │
│       ┆                  ┆ 09:00:38          ┆                 ┆             ┆ 8-afc3-299a91…    │
│ 17722 ┆ 1761330827       ┆ 2025-10-24        ┆ Xcavator.03     ┆ Iglooghost  ┆ 0403cea1-b307-42b │
│       ┆                  ┆ 18:33:47          ┆                 ┆             ┆ b-9025-f6bbb2…    │
│ 17724 ┆ 1761381408       ┆ 2025-10-25        ┆ flux•Cocoon     ┆ Iglooghost  ┆ 8872a941-76d4-487 │
│       ┆                  ┆ 08:36:48          ┆                 ┆             ┆ c-9c26-3782e6…    │
└───────┴──────────────────┴───────────────────┴─────────────────┴─────────────┴───────────────────┘

In [38]:
pl.read_parquet(
        Path("../data/spotify/2017-2021 spotify data.parquet"))

shape: (72_476, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ track_played_u ┆ track_name     ┆ artist_name    ┆ album_name    ┆ date_played_u ┆ spotify_track │
│ tc             ┆ ---            ┆ ---            ┆ ---           ┆ nix           ┆ _uri          │
│ ---            ┆ str            ┆ str            ┆ str           ┆ ---           ┆ ---           │
│ datetime[μs]   ┆                ┆                ┆               ┆ i64           ┆ str           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ 2017-12-17     ┆ Like A G6      ┆ Far East       ┆ Free Wired    ┆ 1513506676    ┆ spotify:track │
│ 10:31:16       ┆                ┆ Movement       ┆               ┆               ┆ :5AyL2kgLtTWE │
│                ┆                ┆                ┆               ┆               ┆ u3qO…         │
│ 2017-12-17     ┆ Rocketeer      ┆ Far East       ┆ Free Wired    ┆ 1513506887    ┆ spotify:track │
│ 10:34:47       ┆                ┆ Movement       ┆               ┆               ┆ :3ZuiIFm9nRnk │
│                ┆                ┆                ┆               ┆               ┆ Rz8A…         │
│ 2017-12-17     ┆ Live My Life   ┆ Far East       ┆ Dirty Bass    ┆ 1513507125    ┆ spotify:track │
│ 10:38:45       ┆                ┆ Movement       ┆               ┆               ┆ :6dpKQiQzZE2r │
│                ┆                ┆                ┆               ┆               ┆ 9rZV…         │
│ 2017-12-17     ┆ Freal Luv      ┆ Far East       ┆ Freal Luv     ┆ 1513507316    ┆ spotify:track │
│ 10:41:56       ┆ (feat.         ┆ Movement       ┆ (feat.        ┆               ┆ :00rbUJGbcjw3 │
│                ┆ Chanyeol & Ti… ┆                ┆ Chanyeol &    ┆               ┆ FW5c…         │
│                ┆                ┆                ┆ Ti…           ┆               ┆               │
│ 2017-12-17     ┆ Turn Up The    ┆ Far East       ┆ Dirty Bass    ┆ 1513507381    ┆ spotify:track │
│ 10:43:01       ┆ Love           ┆ Movement       ┆               ┆               ┆ :4HQ9gXAtONKs │
│                ┆                ┆                ┆               ┆               ┆ 8NCM…         │
│ …              ┆ …              ┆ …              ┆ …             ┆ …             ┆ …             │
│ 2021-05-20     ┆ Xcxoplex (with ┆ A. G. Cook     ┆ Xcxoplex      ┆ 1621491102    ┆ spotify:track │
│ 06:11:42       ┆ Charli XCX)    ┆                ┆ (with Charli  ┆               ┆ :3Qtc8RGzuzbD │
│                ┆                ┆                ┆ XCX)          ┆               ┆ GBpZ…         │
│ 2021-05-20     ┆ Miss The Rage  ┆ Trippie Redd   ┆ Miss The Rage ┆ 1621491339    ┆ spotify:track │
│ 06:15:39       ┆ (feat. Playboi ┆                ┆ (feat.        ┆               ┆ :2BITQ360Knh6 │
│                ┆ C…             ┆                ┆ Playboi C…    ┆               ┆ qNAO…         │
│ 2021-05-20     ┆ The Kiss Of    ┆ Paul McCartney ┆ McCartney III ┆ 1621491483    ┆ spotify:track │
│ 06:18:03       ┆ Venus (Dominic ┆                ┆ Imagined      ┆               ┆ :28kOGtTZzbfQ │
│                ┆ Fik…           ┆                ┆               ┆               ┆ 8fMm…         │
│ 2021-05-20     ┆ Sugar          ┆ Bladee         ┆ Eversince     ┆ 1621491670    ┆ spotify:track │
│ 06:21:10       ┆                ┆                ┆               ┆               ┆ :15lAXvjPkKhk │
│                ┆                ┆                ┆               ┆               ┆ qpgP…         │
│ 2021-05-20     ┆ dead cat       ┆ Teen Suicide   ┆ i will be my  ┆ 1621491788    ┆ spotify:track │
│ 06:23:08       ┆                ┆                ┆ own hell      ┆               ┆ :0GH60OOXzYfU │
│                ┆                ┆                ┆ because …     ┆               ┆ lTUw…         │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

In [ ]:
import polars as pl
def get_artist_table():
    lastfm_df = pl.read_parquet(
    Path("../data/lastfm/lastfm-listening-2021-2026march.parquet"), columns=[
    "date_played_unix", "track_played_utc", "artist_name", "artist_mbid", ]
    )
    spotify_df = pl.read_parquet(
        Path("../data/spotify/2017-2021 spotify data.parquet"),
        columns=["date_played_unix", "track_played_utc", "artist_name"],
    )
    df = pl.concat([ lastfm_df, spotify_df ], how="diagonal").sort(pl.col("date_played_unix"), descending=False)
    df = ( 
        df
        .filter(pl.col("track_played_utc").dt.year() >= 2021)
        .unique(subset=["artist_name"], keep="first")
        .sort("track_played_utc", descending=False)
        .drop_nulls(pl.col("artist_name"))
    )

    return df

get_artist_table()

shape: (4_840, 4)
┌──────────────────┬─────────────────────┬─────────────────────────┬───────────────────────────────┐
│ date_played_unix ┆ track_played_utc    ┆ artist_name             ┆ artist_mbid                   │
│ ---              ┆ ---                 ┆ ---                     ┆ ---                           │
│ i64              ┆ datetime[μs]        ┆ str                     ┆ str                           │
╞══════════════════╪═════════════════════╪═════════════════════════╪═══════════════════════════════╡
│ 1609460125       ┆ 2021-01-01 00:15:25 ┆ The Kid LAROI           ┆ null                          │
│ 1609460335       ┆ 2021-01-01 00:18:55 ┆ TV Girl                 ┆ null                          │
│ 1609504835       ┆ 2021-01-01 12:40:35 ┆ Her's                   ┆ null                          │
│ 1609505050       ┆ 2021-01-01 12:44:10 ┆ Playboi Carti           ┆ null                          │
│ 1609505246       ┆ 2021-01-01 12:47:26 ┆ Pity Party (Girls Club) ┆ null                          │
│ …                ┆ …                   ┆ …                       ┆ …                             │
│ 1774168414       ┆ 2026-03-22 08:33:34 ┆ Dagmar Zuniga           ┆                               │
│ 1774187066       ┆ 2026-03-22 13:44:26 ┆ Tokyo Tea Room          ┆ f836a8dd-6b20-4d95-9e0f-5b758 │
│                  ┆                     ┆                         ┆ f…                            │
│ 1774187541       ┆ 2026-03-22 13:52:21 ┆ Michael Seyer           ┆ 01d243c3-ff03-4470-ae10-a2329 │
│                  ┆                     ┆                         ┆ 8…                            │
│ 1774356202       ┆ 2026-03-24 12:43:22 ┆ Dalton                  ┆ d7806b58-63e9-4875-b49b-72871 │
│                  ┆                     ┆                         ┆ 7…                            │
│ 1774447570       ┆ 2026-03-25 14:06:10 ┆ Donna Lewis             ┆ ba7c4a1c-aa4e-488a-92dc-be92c │
│                  ┆                     ┆                         ┆ b…                            │
└──────────────────┴─────────────────────┴─────────────────────────┴───────────────────────────────┘