In [101]:
import duckdb
import polars as pl
import numpy as np
import pendulum
from pathlib import Path

data_dir = Path("../data/lastfm/listening")
db = duckdb.read_json(data_dir/"*.jsonl")
df = db.pl()

df = df.with_columns(
    pl.from_epoch(
        pl.col("date_played_unix"), time_unit="s"
    ).alias("track_played_utc")
)

print("Raw data:", df.shape)

df = df.unique("date_played_unix") # Not so exact with which duplicate gets removed
print("Duplicate timestamps removed:", df.unique("date_played_unix").shape)
df = df.with_columns(
    artist_name = pl.col("artist_name").str.to_lowercase(),
    track_name = pl.col("track_name").str.to_lowercase(),
    album_name = pl.col("album_name").str.to_lowercase()
)

Raw data: (110513, 8)
Duplicate timestamps removed: (108066, 8)

## Average session length (gap-based clustering)

In [102]:
year = 2025
df_gap = (
    df.sort(pl.col("date_played_unix"), descending=False)
    .filter(pl.col("track_played_utc").dt.year() == year)
    .with_columns(
        played_delta_s = pl.col("date_played_unix").diff().fill_null(0)
    )
).sort(pl.col("played_delta_s"), descending=True)
df_gap

shape: (20_049, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ artist_na ┆ artist_mb ┆ album_nam ┆ album_mbi ┆ … ┆ track_mbi ┆ date_play ┆ track_pla ┆ played_d │
│ me        ┆ id        ┆ e         ┆ d         ┆   ┆ d         ┆ ed_unix   ┆ yed_utc   ┆ elta_s   │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ i64       ┆ datetime[ ┆ i64      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ μs]       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ kettama   ┆ e457531c- ┆ yosemite  ┆           ┆ … ┆           ┆ 173589418 ┆ 2025-01-0 ┆ 131901   │
│           ┆ 4add-45f0 ┆           ┆           ┆   ┆           ┆ 8         ┆ 3         ┆          │
│           ┆ -9998-f65 ┆           ┆           ┆   ┆           ┆           ┆ 08:49:48  ┆          │
│           ┆ ec5…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ astrid    ┆ bc6af694- ┆ great     ┆ df87374d- ┆ … ┆ b38a04eb- ┆ 175428617 ┆ 2025-08-0 ┆ 107218   │
│ sonne     ┆ 5880-4770 ┆ doubt     ┆ 53df-48d9 ┆   ┆ 3543-4286 ┆ 0         ┆ 4         ┆          │
│           ┆ -bdf1-82d ┆           ┆ -9677-ae3 ┆   ┆ -add0-a81 ┆           ┆ 05:42:50  ┆          │
│           ┆ 03f…      ┆           ┆ 297…      ┆   ┆ 315…      ┆           ┆           ┆          │
│ fcukers   ┆ 5e23e428- ┆ bon bon   ┆ 7758de6f- ┆ … ┆ 864c5765- ┆ 175241852 ┆ 2025-07-1 ┆ 100913   │
│           ┆ d9f5-4679 ┆           ┆ d039-4672 ┆   ┆ 1c94-489a ┆ 7         ┆ 3         ┆          │
│           ┆ -bd7c-825 ┆           ┆ -ac4b-2c3 ┆   ┆ -80d7-755 ┆           ┆ 14:55:27  ┆          │
│           ┆ 4d6…      ┆           ┆ 0fc…      ┆   ┆ 7de…      ┆           ┆           ┆          │
│ fred      ┆ bca46a0c- ┆ actual    ┆ f50f4e97- ┆ … ┆ 9a3467f6- ┆ 176670050 ┆ 2025-12-2 ┆ 83148    │
│ again..   ┆ 25c9-42ca ┆ life 2    ┆ 8a6d-4212 ┆   ┆ 4fd8-45f8 ┆ 5         ┆ 5         ┆          │
│           ┆ -98c2-e64 ┆ (february ┆ -a710-e82 ┆   ┆ -a855-e55 ┆           ┆ 22:08:25  ┆          │
│           ┆ c8a…      ┆ 2 - oc…   ┆ caf…      ┆   ┆ 2c0…      ┆           ┆           ┆          │
│ yung lean ┆           ┆ forever   ┆           ┆ … ┆           ┆ 174033068 ┆ 2025-02-2 ┆ 81702    │
│           ┆           ┆ yung      ┆           ┆   ┆           ┆ 0         ┆ 3         ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 17:11:20  ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ caroline  ┆ d8f43dc5- ┆ pang      ┆ 3913f9b2- ┆ … ┆ 552cf74f- ┆ 176596515 ┆ 2025-12-1 ┆ 1        │
│ polachek  ┆ 4613-48ac ┆           ┆ 8622-4b0b ┆   ┆ 2de3-46c5 ┆ 0         ┆ 7         ┆          │
│           ┆ -8c23-a62 ┆           ┆ -aeb5-351 ┆   ┆ -8adb-395 ┆           ┆ 09:52:30  ┆          │
│           ┆ b82…      ┆           ┆ 1d2…      ┆   ┆ 5a0…      ┆           ┆           ┆          │
│ lover's   ┆           ┆ all       ┆           ┆ … ┆           ┆ 176596532 ┆ 2025-12-1 ┆ 1        │
│ skit      ┆           ┆ rights    ┆           ┆   ┆           ┆ 8         ┆ 7         ┆          │
│           ┆           ┆ remixed   ┆           ┆   ┆           ┆           ┆ 09:55:28  ┆          │
│ amelie    ┆ 67db280d- ┆ higher ep ┆ ab5756fb- ┆ … ┆           ┆ 176631637 ┆ 2025-12-2 ┆ 1        │
│ lens      ┆ c3e4-49d9 ┆           ┆ afda-434e ┆   ┆           ┆ 1         ┆ 1         ┆          │
│           ┆ -978e-405 ┆           ┆ -906a-4fb ┆   ┆           ┆           ┆ 11:26:11  ┆          │
│           ┆ 0f4…      ┆           ┆ ca0…      ┆   ┆           ┆           ┆           ┆          │
│ fred      ┆ bca46a0c- ┆ actual    ┆ f50f4e97- ┆ … ┆ 9a3467f6- ┆ 176633105 ┆ 2025-12-2 ┆ 1        │
│ again..   ┆ 25c9-42ca ┆ life 2    ┆ 8a6d-4212 ┆   ┆ 4fd8-45f8 ┆ 1         ┆ 1         ┆          │
│           ┆ -98c2-e64 ┆ (february ┆ -a710-e82 ┆   ┆ -a855-e55 ┆           ┆ 15:30:51  ┆          │
│           ┆ c8a…      ┆ 2 - oc…   ┆ caf…      ┆   ┆ 2c0…      ┆           ┆           ┆          │
│ brutalism ┆ b4cd749e- ┆ goodbye   ┆           ┆ … ┆ a8902a2d- ┆ 173569366 ┆ 2025-01-0 ┆ 0        │
│ us 3000   ┆ adce-4cb5 ┆ salò      ┆           ┆   ┆ 906d-4595 ┆ 7         ┆ 1         ┆          │
│           ┆ -8a73-cdd ┆           ┆           ┆   ┆ -ac0e-684 ┆           ┆ 01:07:47  ┆          │
│           ┆ 0c7…      ┆           ┆           ┆   ┆ 59c…      ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [103]:
custom_bins = np.arange(0, 86400+1, 600)
bin_count, bins = np.histogram(
    df_gap.select(pl.col("played_delta_s")).to_numpy().flatten(),
    # 200
    custom_bins
)
print(bin_count)
print(bins)

[16843   791   389   256   216   175   148   100    89    76    63    54
    50    39    30    41    39    29    28    27    19    20    17    20
    13    11    15     9     8     7     7     2     3     2     4     2
     3     2     6     3     5     3     3     3     3     0     2     3
     2     8     7     4     2     3     4     7     7     3     7     9
     9    11    16     7    11     9    13    13    14    17     9     7
     5     8     8    14     7    10    10     6     5     1     6     8
     4     4    12     4     2     3     2     7     3     1     4     3
     2     1     2     2     2     1     2     2     1     1     0     0
     1     4     1     0     1     0     0     1     1     0     1     0
     1     0     0     0     0     0     1     0     0     0     0     0
     0     0     1     1     1     0     1     0     0     0     0     0]
[    0   600  1200  1800  2400  3000  3600  4200  4800  5400  6000  6600
  7200  7800  8400  9000  9600 10200 10800 11400 12000 12600 13200 13800
 14400 15000 15600 16200 16800 17400 18000 18600 19200 19800 20400 21000
 21600 22200 22800 23400 24000 24600 25200 25800 26400 27000 27600 28200
 28800 29400 30000 30600 31200 31800 32400 33000 33600 34200 34800 35400
 36000 36600 37200 37800 38400 39000 39600 40200 40800 41400 42000 42600
 43200 43800 44400 45000 45600 46200 46800 47400 48000 48600 49200 49800
 50400 51000 51600 52200 52800 53400 54000 54600 55200 55800 56400 57000
 57600 58200 58800 59400 60000 60600 61200 61800 62400 63000 63600 64200
 64800 65400 66000 66600 67200 67800 68400 69000 69600 70200 70800 71400
 72000 72600 73200 73800 74400 75000 75600 76200 76800 77400 78000 78600
 79200 79800 80400 81000 81600 82200 82800 83400 84000 84600 85200 85800
 86400]

We will set 10 minutes (600s) as our threshold for what consitutes as a new listening session.

In [104]:
threshold = 1800 # 3600
# threshold = 3600 # 3600
df_sessions = (
    df_gap
    .sort(pl.col("date_played_unix"), descending=False)
    .with_columns(
        (pl.col("played_delta_s") > threshold).alias("exceeds")
    )
    .with_columns(pl.col("exceeds").cum_sum().alias("nth_session"))
    .drop("exceeds")
    # count
    # .group_by(pl.col("track_played_utc"), pl.col("nth_session"))
    # .agg(
    #     n_scrobbles = pl.len()
    # )
    # .sort(pl.col("track_played_utc"), descending=False)
    # .with_columns(
    #     nth_scrobble = pl.col("n_scrobbles").cum_sum()
    # )
)
df_sessions.head(10)

shape: (10, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ artist_na ┆ artist_mb ┆ album_nam ┆ album_mbi ┆ … ┆ date_play ┆ track_pla ┆ played_de ┆ nth_sess │
│ me        ┆ id        ┆ e         ┆ d         ┆   ┆ ed_unix   ┆ yed_utc   ┆ lta_s     ┆ ion      │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ i64       ┆ datetime[ ┆ i64       ┆ u32      │
│           ┆           ┆           ┆           ┆   ┆           ┆ μs]       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ brutalism ┆ b4cd749e- ┆ goodbye   ┆           ┆ … ┆ 173569366 ┆ 2025-01-0 ┆ 0         ┆ 0        │
│ us 3000   ┆ adce-4cb5 ┆ salò      ┆           ┆   ┆ 7         ┆ 1         ┆           ┆          │
│           ┆ -8a73-cdd ┆           ┆           ┆   ┆           ┆ 01:07:47  ┆           ┆          │
│           ┆ 0c7…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mutilator ┆ b239fbf8- ┆ can you   ┆           ┆ … ┆ 173569382 ┆ 2025-01-0 ┆ 160       ┆ 0        │
│           ┆ 782b-4dc0 ┆ feel it?! ┆           ┆   ┆ 7         ┆ 1         ┆           ┆          │
│           ┆ -85eb-3ff ┆           ┆           ┆   ┆           ┆ 01:10:27  ┆           ┆          │
│           ┆ 4d6…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ snow      ┆ 33243fef- ┆ april     ┆ 3c39c467- ┆ … ┆ 173569411 ┆ 2025-01-0 ┆ 286       ┆ 0        │
│ strippers ┆ ce1a-4ba7 ┆ mixtape 2 ┆ 3e37-4a41 ┆   ┆ 3         ┆ 1         ┆           ┆          │
│           ┆ -a81e-ec7 ┆           ┆ -b530-b68 ┆   ┆           ┆ 01:15:13  ┆           ┆          │
│           ┆ 2e4…      ┆           ┆ 429…      ┆   ┆           ┆           ┆           ┆          │
│ underscor ┆ ab1a3f85- ┆ wallsocke ┆ 06efd7a6- ┆ … ┆ 173569427 ┆ 2025-01-0 ┆ 163       ┆ 0        │
│ es        ┆ e0ea-470a ┆ t (direct ┆ f6ee-406d ┆   ┆ 6         ┆ 1         ┆           ┆          │
│           ┆ -af5c-175 ┆ or's cut) ┆ -8575-2c5 ┆   ┆           ┆ 01:17:56  ┆           ┆          │
│           ┆ 447…      ┆           ┆ 2a0…      ┆   ┆           ┆           ┆           ┆          │
│ smino     ┆           ┆ maybe in  ┆           ┆ … ┆ 173575428 ┆ 2025-01-0 ┆ 60012     ┆ 1        │
│           ┆           ┆ nirvana   ┆           ┆   ┆ 8         ┆ 1         ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 17:58:08  ┆           ┆          │
│ saga bouy ┆           ┆ scary     ┆           ┆ … ┆ 173575581 ┆ 2025-01-0 ┆ 1525      ┆ 1        │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 1         ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 18:23:33  ┆           ┆          │
│ saga bouy ┆           ┆ scary     ┆           ┆ … ┆ 173576228 ┆ 2025-01-0 ┆ 6474      ┆ 2        │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 1         ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 20:11:27  ┆           ┆          │
│ kettama   ┆ e457531c- ┆ yosemite  ┆           ┆ … ┆ 173589418 ┆ 2025-01-0 ┆ 131901    ┆ 3        │
│           ┆ 4add-45f0 ┆           ┆           ┆   ┆ 8         ┆ 3         ┆           ┆          │
│           ┆ -9998-f65 ┆           ┆           ┆   ┆           ┆ 08:49:48  ┆           ┆          │
│           ┆ ec5…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ eliza     ┆ afd9baa6- ┆ b.o.t.a.  ┆           ┆ … ┆ 173589445 ┆ 2025-01-0 ┆ 265       ┆ 3        │
│ rose      ┆ 4402-40c8 ┆ (baddest  ┆           ┆   ┆ 3         ┆ 3         ┆           ┆          │
│           ┆ -91ad-d79 ┆ of them   ┆           ┆   ┆           ┆ 08:54:13  ┆           ┆          │
│           ┆ 2ae…      ┆ all)…     ┆           ┆   ┆           ┆           ┆           ┆          │
│ mall grab ┆ 845ddc8b- ┆ found     ┆           ┆ … ┆ 173589481 ┆ 2025-01-0 ┆ 359       ┆ 3        │
│           ┆ 36ba-4d7b ┆ ourselves ┆           ┆   ┆ 2         ┆ 3         ┆           ┆          │
│           ┆ -9c6f-bd7 ┆           ┆           ┆   ┆           ┆ 09:00:12  ┆           ┆          │
│           ┆ 623…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Session statistics

In [105]:
df_session_stats = ( 
    df_sessions 
    .group_by(pl.col("nth_session"))
    .agg(
        session_mean_s = pl.col("played_delta_s").mean(),
        tracks_played = pl.col("played_delta_s").count(),
        session_start = pl.col("track_played_utc").min(),
        session_end = pl.col("track_played_utc").max(),
    )
    .with_columns(
        session_length = (pl.col("session_end") - pl.col("session_start"))# .dt.total_seconds()
    )
    .filter(pl.col("session_length") > pl.duration(hours=3))
).sort(pl.col("session_start"))
df_session_stats.sort(pl.col("session_length"), descending=True)

shape: (73, 6)
┌─────────────┬────────────────┬───────────────┬─────────────────┬────────────────┬────────────────┐
│ nth_session ┆ session_mean_s ┆ tracks_played ┆ session_start   ┆ session_end    ┆ session_length │
│ ---         ┆ ---            ┆ ---           ┆ ---             ┆ ---            ┆ ---            │
│ u32         ┆ f64            ┆ u32           ┆ datetime[μs]    ┆ datetime[μs]   ┆ duration[μs]   │
╞═════════════╪════════════════╪═══════════════╪═════════════════╪════════════════╪════════════════╡
│ 914         ┆ 332.760479     ┆ 167           ┆ 2025-06-12      ┆ 2025-06-12     ┆ 10h 1m 43s     │
│             ┆                ┆               ┆ 06:09:46        ┆ 16:11:29       ┆                │
│ 58          ┆ 233.576923     ┆ 130           ┆ 2025-01-13      ┆ 2025-01-13     ┆ 7h 5m 28s      │
│             ┆                ┆               ┆ 07:00:56        ┆ 14:06:24       ┆                │
│ 311         ┆ 290.715909     ┆ 88            ┆ 2025-02-27      ┆ 2025-02-27     ┆ 6h 14m 56s     │
│             ┆                ┆               ┆ 07:24:08        ┆ 13:39:04       ┆                │
│ 213         ┆ 266.295918     ┆ 98            ┆ 2025-02-07      ┆ 2025-02-07     ┆ 6h 12m 41s     │
│             ┆                ┆               ┆ 06:44:35        ┆ 12:57:16       ┆                │
│ 354         ┆ 238.768519     ┆ 108           ┆ 2025-03-07      ┆ 2025-03-07     ┆ 6h 7m 22s      │
│             ┆                ┆               ┆ 07:10:54        ┆ 13:18:16       ┆                │
│ …           ┆ …              ┆ …             ┆ …               ┆ …              ┆ …              │
│ 963         ┆ 508.75         ┆ 44            ┆ 2025-06-19      ┆ 2025-06-19     ┆ 3h 4m 19s      │
│             ┆                ┆               ┆ 14:44:15        ┆ 17:48:34       ┆                │
│ 719         ┆ 1032.489362    ┆ 47            ┆ 2025-05-12      ┆ 2025-05-12     ┆ 3h 3m          │
│             ┆                ┆               ┆ 06:51:30        ┆ 09:54:30       ┆                │
│ 1586        ┆ 311.634146     ┆ 41            ┆ 2025-10-10      ┆ 2025-10-10     ┆ 3h 2m 18s      │
│             ┆                ┆               ┆ 07:18:27        ┆ 10:20:45       ┆                │
│ 509         ┆ 274.962264     ┆ 53            ┆ 2025-04-02      ┆ 2025-04-02     ┆ 3h 38s         │
│             ┆                ┆               ┆ 11:01:54        ┆ 14:02:32       ┆                │
│ 668         ┆ 360.102564     ┆ 39            ┆ 2025-05-01      ┆ 2025-05-01     ┆ 3h 36s         │
│             ┆                ┆               ┆ 07:23:17        ┆ 10:23:53       ┆                │
└─────────────┴────────────────┴───────────────┴─────────────────┴────────────────┴────────────────┘

In [106]:
import plotly.express as px
fig = px.timeline(df_session_stats, x_start="session_start", x_end="session_end", color="session_length")
fig.show()

In [109]:
# Average session length
df_session_stats.select(pl.col("session_length").mean().alias("avg_session_length"))

shape: (1, 1)
┌─────────────────────┐
│ avg_session_length  │
│ ---                 │
│ duration[μs]        │
╞═════════════════════╡
│ 4h 16m 57s 150684µs │
└─────────────────────┘