In [1]:
import duckdb
import polars as pl
import numpy as np
import pendulum
from pathlib import Path

data_dir = Path("../data/lastfm/listening")
db = duckdb.read_json(data_dir/"*.jsonl")
df = db.pl()

df = df.with_columns(
    pl.from_epoch(
        pl.col("date_played_unix"), time_unit="s"
    ).alias("track_played_utc")
)

print("Raw data:", df.shape)

df = df.unique("date_played_unix") # Not so exact with which duplicate gets removed
print("Duplicate timestamps removed:", df.unique("date_played_unix").shape)
df = df.with_columns(
    artist_name = pl.col("artist_name").str.to_lowercase(),
    track_name = pl.col("track_name").str.to_lowercase(),
    album_name = pl.col("album_name").str.to_lowercase()
)

Raw data: (110513, 8)
Duplicate timestamps removed: (108066, 8)

## Average session length (gap-based clustering)

In [2]:
year = 2025
df_gap = (
    df.sort(pl.col("date_played_unix"), descending=False)
    .filter(pl.col("track_played_utc").dt.year() == year)
    .with_columns(
        played_delta_s = pl.col("date_played_unix").diff().fill_null(0)
    )
).sort(pl.col("played_delta_s"), descending=True)
df_gap

shape: (20_049, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ artist_na ┆ artist_mb ┆ album_nam ┆ album_mbi ┆ … ┆ track_mbi ┆ date_play ┆ track_pla ┆ played_d │
│ me        ┆ id        ┆ e         ┆ d         ┆   ┆ d         ┆ ed_unix   ┆ yed_utc   ┆ elta_s   │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ i64       ┆ datetime[ ┆ i64      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ μs]       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ kettama   ┆ e457531c- ┆ yosemite  ┆           ┆ … ┆           ┆ 173589418 ┆ 2025-01-0 ┆ 131901   │
│           ┆ 4add-45f0 ┆           ┆           ┆   ┆           ┆ 8         ┆ 3         ┆          │
│           ┆ -9998-f65 ┆           ┆           ┆   ┆           ┆           ┆ 08:49:48  ┆          │
│           ┆ ec5…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ astrid    ┆ bc6af694- ┆ great     ┆ df87374d- ┆ … ┆ b38a04eb- ┆ 175428617 ┆ 2025-08-0 ┆ 107218   │
│ sonne     ┆ 5880-4770 ┆ doubt     ┆ 53df-48d9 ┆   ┆ 3543-4286 ┆ 0         ┆ 4         ┆          │
│           ┆ -bdf1-82d ┆           ┆ -9677-ae3 ┆   ┆ -add0-a81 ┆           ┆ 05:42:50  ┆          │
│           ┆ 03f…      ┆           ┆ 297…      ┆   ┆ 315…      ┆           ┆           ┆          │
│ fcukers   ┆ 5e23e428- ┆ bon bon   ┆ 7758de6f- ┆ … ┆ 864c5765- ┆ 175241852 ┆ 2025-07-1 ┆ 100913   │
│           ┆ d9f5-4679 ┆           ┆ d039-4672 ┆   ┆ 1c94-489a ┆ 7         ┆ 3         ┆          │
│           ┆ -bd7c-825 ┆           ┆ -ac4b-2c3 ┆   ┆ -80d7-755 ┆           ┆ 14:55:27  ┆          │
│           ┆ 4d6…      ┆           ┆ 0fc…      ┆   ┆ 7de…      ┆           ┆           ┆          │
│ fred      ┆ bca46a0c- ┆ actual    ┆ f50f4e97- ┆ … ┆ 9a3467f6- ┆ 176670050 ┆ 2025-12-2 ┆ 83148    │
│ again..   ┆ 25c9-42ca ┆ life 2    ┆ 8a6d-4212 ┆   ┆ 4fd8-45f8 ┆ 5         ┆ 5         ┆          │
│           ┆ -98c2-e64 ┆ (february ┆ -a710-e82 ┆   ┆ -a855-e55 ┆           ┆ 22:08:25  ┆          │
│           ┆ c8a…      ┆ 2 - oc…   ┆ caf…      ┆   ┆ 2c0…      ┆           ┆           ┆          │
│ yung lean ┆           ┆ forever   ┆           ┆ … ┆           ┆ 174033068 ┆ 2025-02-2 ┆ 81702    │
│           ┆           ┆ yung      ┆           ┆   ┆           ┆ 0         ┆ 3         ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 17:11:20  ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ caroline  ┆ d8f43dc5- ┆ pang      ┆ 3913f9b2- ┆ … ┆ 552cf74f- ┆ 176596515 ┆ 2025-12-1 ┆ 1        │
│ polachek  ┆ 4613-48ac ┆           ┆ 8622-4b0b ┆   ┆ 2de3-46c5 ┆ 0         ┆ 7         ┆          │
│           ┆ -8c23-a62 ┆           ┆ -aeb5-351 ┆   ┆ -8adb-395 ┆           ┆ 09:52:30  ┆          │
│           ┆ b82…      ┆           ┆ 1d2…      ┆   ┆ 5a0…      ┆           ┆           ┆          │
│ lover's   ┆           ┆ all       ┆           ┆ … ┆           ┆ 176596532 ┆ 2025-12-1 ┆ 1        │
│ skit      ┆           ┆ rights    ┆           ┆   ┆           ┆ 8         ┆ 7         ┆          │
│           ┆           ┆ remixed   ┆           ┆   ┆           ┆           ┆ 09:55:28  ┆          │
│ amelie    ┆ 67db280d- ┆ higher ep ┆ ab5756fb- ┆ … ┆           ┆ 176631637 ┆ 2025-12-2 ┆ 1        │
│ lens      ┆ c3e4-49d9 ┆           ┆ afda-434e ┆   ┆           ┆ 1         ┆ 1         ┆          │
│           ┆ -978e-405 ┆           ┆ -906a-4fb ┆   ┆           ┆           ┆ 11:26:11  ┆          │
│           ┆ 0f4…      ┆           ┆ ca0…      ┆   ┆           ┆           ┆           ┆          │
│ fred      ┆ bca46a0c- ┆ actual    ┆ f50f4e97- ┆ … ┆ 9a3467f6- ┆ 176633105 ┆ 2025-12-2 ┆ 1        │
│ again..   ┆ 25c9-42ca ┆ life 2    ┆ 8a6d-4212 ┆   ┆ 4fd8-45f8 ┆ 1         ┆ 1         ┆          │
│           ┆ -98c2-e64 ┆ (february ┆ -a710-e82 ┆   ┆ -a855-e55 ┆           ┆ 15:30:51  ┆          │
│           ┆ c8a…      ┆ 2 - oc…   ┆ caf…      ┆   ┆ 2c0…      ┆           ┆           ┆          │
│ brutalism ┆ b4cd749e- ┆ goodbye   ┆           ┆ … ┆ a8902a2d- ┆ 173569366 ┆ 2025-01-0 ┆ 0        │
│ us 3000   ┆ adce-4cb5 ┆ salò      ┆           ┆   ┆ 906d-4595 ┆ 7         ┆ 1         ┆          │
│           ┆ -8a73-cdd ┆           ┆           ┆   ┆ -ac0e-684 ┆           ┆ 01:07:47  ┆          │
│           ┆ 0c7…      ┆           ┆           ┆   ┆ 59c…      ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [3]:
custom_bins = np.arange(0, 86400+1, 600)
bin_count, bins = np.histogram(
    df_gap.select(pl.col("played_delta_s")).to_numpy().flatten(),
    # 200
    custom_bins
)
print(bin_count)
print(bins)

[16843   791   389   256   216   175   148   100    89    76    63    54
    50    39    30    41    39    29    28    27    19    20    17    20
    13    11    15     9     8     7     7     2     3     2     4     2
     3     2     6     3     5     3     3     3     3     0     2     3
     2     8     7     4     2     3     4     7     7     3     7     9
     9    11    16     7    11     9    13    13    14    17     9     7
     5     8     8    14     7    10    10     6     5     1     6     8
     4     4    12     4     2     3     2     7     3     1     4     3
     2     1     2     2     2     1     2     2     1     1     0     0
     1     4     1     0     1     0     0     1     1     0     1     0
     1     0     0     0     0     0     1     0     0     0     0     0
     0     0     1     1     1     0     1     0     0     0     0     0]
[    0   600  1200  1800  2400  3000  3600  4200  4800  5400  6000  6600
  7200  7800  8400  9000  9600 10200 10800 11400 12000 12600 13200 13800
 14400 15000 15600 16200 16800 17400 18000 18600 19200 19800 20400 21000
 21600 22200 22800 23400 24000 24600 25200 25800 26400 27000 27600 28200
 28800 29400 30000 30600 31200 31800 32400 33000 33600 34200 34800 35400
 36000 36600 37200 37800 38400 39000 39600 40200 40800 41400 42000 42600
 43200 43800 44400 45000 45600 46200 46800 47400 48000 48600 49200 49800
 50400 51000 51600 52200 52800 53400 54000 54600 55200 55800 56400 57000
 57600 58200 58800 59400 60000 60600 61200 61800 62400 63000 63600 64200
 64800 65400 66000 66600 67200 67800 68400 69000 69600 70200 70800 71400
 72000 72600 73200 73800 74400 75000 75600 76200 76800 77400 78000 78600
 79200 79800 80400 81000 81600 82200 82800 83400 84000 84600 85200 85800
 86400]

We will set 10 minutes (600s) as our threshold for what consitutes as a new listening session.

In [4]:
threshold = 20*60 # 3600
# threshold = 3600 # 3600
df_sessions = (
    df_gap
    .sort(pl.col("date_played_unix"), descending=False)
    .with_columns(
        (pl.col("played_delta_s") > threshold).alias("exceeds")
    )
    .with_columns(pl.col("exceeds").cum_sum().alias("nth_session"))
    .with_columns(
        pl.when(pl.col("exceeds"))
        .then(0)
        .otherwise(pl.col("played_delta_s"))
        .alias("played_delta_s")
    ) # set first song of session to 0
    .drop("exceeds")
    # count
    # .group_by(pl.col("track_played_utc"), pl.col("nth_session"))
    # .agg(
    #     n_scrobbles = pl.len()
    # )
    # .sort(pl.col("track_played_utc"), descending=False)
    # .with_columns(
    #     nth_scrobble = pl.col("n_scrobbles").cum_sum()
    # )
)

### Session statistics

In [5]:
df_session_stats = ( 
    df_sessions 
    .group_by(pl.col("nth_session"))
    .agg(
        # session_mean_s = pl.col("played_delta_s").mean(),
        tracks_played = pl.col("played_delta_s").count(),
        session_start = pl.col("track_played_utc").min(),
        session_end = pl.col("track_played_utc").max(),
    )
    .with_columns(
        session_length = (pl.col("session_end") - pl.col("session_start")),# .dt.total_seconds()
        date_played_utc = pl.col("session_end").dt.date()
    )
    # .filter(pl.col("session_length") > pl.duration(hours=3))
    .sort(pl.col("session_start"))
)
df_session_stats.sort(pl.col("session_length"), descending=True)

shape: (2_416, 6)
┌─────────────┬───────────────┬─────────────────┬────────────────┬────────────────┬────────────────┐
│ nth_session ┆ tracks_played ┆ session_start   ┆ session_end    ┆ session_length ┆ date_played_ut │
│ ---         ┆ ---           ┆ ---             ┆ ---            ┆ ---            ┆ c              │
│ u32         ┆ u32           ┆ datetime[μs]    ┆ datetime[μs]   ┆ duration[μs]   ┆ ---            │
│             ┆               ┆                 ┆                ┆                ┆ date           │
╞═════════════╪═══════════════╪═════════════════╪════════════════╪════════════════╪════════════════╡
│ 384         ┆ 88            ┆ 2025-02-27      ┆ 2025-02-27     ┆ 6h 14m 56s     ┆ 2025-02-27     │
│             ┆               ┆ 07:24:08        ┆ 13:39:04       ┆                ┆                │
│ 435         ┆ 108           ┆ 2025-03-07      ┆ 2025-03-07     ┆ 6h 7m 22s      ┆ 2025-03-07     │
│             ┆               ┆ 07:10:54        ┆ 13:18:16       ┆                ┆                │
│ 411         ┆ 89            ┆ 2025-03-03      ┆ 2025-03-03     ┆ 5h 48m 13s     ┆ 2025-03-03     │
│             ┆               ┆ 06:50:11        ┆ 12:38:24       ┆                ┆                │
│ 538         ┆ 72            ┆ 2025-03-21      ┆ 2025-03-21     ┆ 5h 39m 51s     ┆ 2025-03-21     │
│             ┆               ┆ 08:13:38        ┆ 13:53:29       ┆                ┆                │
│ 233         ┆ 82            ┆ 2025-02-03      ┆ 2025-02-03     ┆ 5h 35m 31s     ┆ 2025-02-03     │
│             ┆               ┆ 08:17:12        ┆ 13:52:43       ┆                ┆                │
│ …           ┆ …             ┆ …               ┆ …              ┆ …              ┆ …              │
│ 2400        ┆ 1             ┆ 2025-12-27      ┆ 2025-12-27     ┆ 0µs            ┆ 2025-12-27     │
│             ┆               ┆ 09:55:32        ┆ 09:55:32       ┆                ┆                │
│ 2401        ┆ 1             ┆ 2025-12-27      ┆ 2025-12-27     ┆ 0µs            ┆ 2025-12-27     │
│             ┆               ┆ 15:19:30        ┆ 15:19:30       ┆                ┆                │
│ 2408        ┆ 1             ┆ 2025-12-30      ┆ 2025-12-30     ┆ 0µs            ┆ 2025-12-30     │
│             ┆               ┆ 12:45:08        ┆ 12:45:08       ┆                ┆                │
│ 2409        ┆ 1             ┆ 2025-12-30      ┆ 2025-12-30     ┆ 0µs            ┆ 2025-12-30     │
│             ┆               ┆ 14:19:00        ┆ 14:19:00       ┆                ┆                │
│ 2411        ┆ 1             ┆ 2025-12-30      ┆ 2025-12-30     ┆ 0µs            ┆ 2025-12-30     │
│             ┆               ┆ 17:35:49        ┆ 17:35:49       ┆                ┆                │
└─────────────┴───────────────┴─────────────────┴────────────────┴────────────────┴────────────────┘

In [6]:
import plotly.express as px
fig = px.timeline(df_session_stats, x_start="session_start", x_end="session_end", color="session_length")
fig.show()

In [7]:
# Average session length
df_session_stats.select(pl.col("session_length").mean().alias("avg_session_length"))

shape: (1, 1)
┌────────────────────┐
│ avg_session_length │
│ ---                │
│ duration[μs]       │
╞════════════════════╡
│ 27m 36s 512003µs   │
└────────────────────┘

In [8]:
df_sessions.group_by(pl.col("nth_session")).agg(session_length_s = pl.col("played_delta_s").sum()/3600).sort("session_length_s", descending=True)

shape: (2_416, 2)
┌─────────────┬──────────────────┐
│ nth_session ┆ session_length_s │
│ ---         ┆ ---              │
│ u32         ┆ f64              │
╞═════════════╪══════════════════╡
│ 384         ┆ 6.248889         │
│ 435         ┆ 6.122778         │
│ 411         ┆ 5.803611         │
│ 538         ┆ 5.664167         │
│ 233         ┆ 5.591944         │
│ …           ┆ …                │
│ 2209        ┆ 0.0              │
│ 1956        ┆ 0.0              │
│ 1807        ┆ 0.0              │
│ 1155        ┆ 0.0              │
│ 1045        ┆ 0.0              │
└─────────────┴──────────────────┘

In [9]:
( 
    df_sessions 
    .group_by(pl.col("track_played_utc").dt.date().alias("date_played_utc"))
    .agg(
        n_sessions = pl.col("nth_session").unique().len()
    )
    # .sort(pl.col("track_played_utc"), descending=False)
    .sort(pl.col("n_sessions"), descending=True)
).join(df_session_stats, "date_played_utc", how="right").sort("n_sessions", descending=False).sort("session_length", descending=True)

shape: (2_416, 7)
┌────────────┬─────────────┬──────────────┬──────────────┬─────────────┬─────────────┬─────────────┐
│ n_sessions ┆ nth_session ┆ tracks_playe ┆ session_star ┆ session_end ┆ session_len ┆ date_played │
│ ---        ┆ ---         ┆ d            ┆ t            ┆ ---         ┆ gth         ┆ _utc        │
│ u32        ┆ u32         ┆ ---          ┆ ---          ┆ datetime[μs ┆ ---         ┆ ---         │
│            ┆             ┆ u32          ┆ datetime[μs] ┆ ]           ┆ duration[μs ┆ date        │
│            ┆             ┆              ┆              ┆             ┆ ]           ┆             │
╞════════════╪═════════════╪══════════════╪══════════════╪═════════════╪═════════════╪═════════════╡
│ 5          ┆ 384         ┆ 88           ┆ 2025-02-27   ┆ 2025-02-27  ┆ 6h 14m 56s  ┆ 2025-02-27  │
│            ┆             ┆              ┆ 07:24:08     ┆ 13:39:04    ┆             ┆             │
│ 9          ┆ 435         ┆ 108          ┆ 2025-03-07   ┆ 2025-03-07  ┆ 6h 7m 22s   ┆ 2025-03-07  │
│            ┆             ┆              ┆ 07:10:54     ┆ 13:18:16    ┆             ┆             │
│ 4          ┆ 411         ┆ 89           ┆ 2025-03-03   ┆ 2025-03-03  ┆ 5h 48m 13s  ┆ 2025-03-03  │
│            ┆             ┆              ┆ 06:50:11     ┆ 12:38:24    ┆             ┆             │
│ 7          ┆ 538         ┆ 72           ┆ 2025-03-21   ┆ 2025-03-21  ┆ 5h 39m 51s  ┆ 2025-03-21  │
│            ┆             ┆              ┆ 08:13:38     ┆ 13:53:29    ┆             ┆             │
│ 8          ┆ 233         ┆ 82           ┆ 2025-02-03   ┆ 2025-02-03  ┆ 5h 35m 31s  ┆ 2025-02-03  │
│            ┆             ┆              ┆ 08:17:12     ┆ 13:52:43    ┆             ┆             │
│ …          ┆ …           ┆ …            ┆ …            ┆ …           ┆ …           ┆ …           │
│ 13         ┆ 481         ┆ 1            ┆ 2025-03-14   ┆ 2025-03-14  ┆ 0µs         ┆ 2025-03-14  │
│            ┆             ┆              ┆ 05:52:46     ┆ 05:52:46    ┆             ┆             │
│ 13         ┆ 485         ┆ 1            ┆ 2025-03-14   ┆ 2025-03-14  ┆ 0µs         ┆ 2025-03-14  │
│            ┆             ┆              ┆ 10:59:49     ┆ 10:59:49    ┆             ┆             │
│ 13         ┆ 486         ┆ 1            ┆ 2025-03-14   ┆ 2025-03-14  ┆ 0µs         ┆ 2025-03-14  │
│            ┆             ┆              ┆ 11:32:31     ┆ 11:32:31    ┆             ┆             │
│ 13         ┆ 489         ┆ 1            ┆ 2025-03-14   ┆ 2025-03-14  ┆ 0µs         ┆ 2025-03-14  │
│            ┆             ┆              ┆ 15:20:29     ┆ 15:20:29    ┆             ┆             │
│ 13         ┆ 492         ┆ 1            ┆ 2025-03-14   ┆ 2025-03-14  ┆ 0µs         ┆ 2025-03-14  │
│            ┆             ┆              ┆ 22:12:27     ┆ 22:12:27    ┆             ┆             │
└────────────┴─────────────┴──────────────┴──────────────┴─────────────┴─────────────┴─────────────┘

In [10]:

df_sessions.filter(pl.col("track_played_utc").dt.date() == pendulum.datetime(2025, 1, 20).naive())

shape: (99, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ artist_na ┆ artist_mb ┆ album_nam ┆ album_mbi ┆ … ┆ date_play ┆ track_pla ┆ played_de ┆ nth_sess │
│ me        ┆ id        ┆ e         ┆ d         ┆   ┆ ed_unix   ┆ yed_utc   ┆ lta_s     ┆ ion      │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ i64       ┆ datetime[ ┆ i64       ┆ u32      │
│           ┆           ┆           ┆           ┆   ┆           ┆ μs]       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ dj suzy   ┆           ┆ digital   ┆           ┆ … ┆ 173736520 ┆ 2025-01-2 ┆ 0         ┆ 120      │
│           ┆           ┆ girl      ┆           ┆   ┆ 8         ┆ 0         ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 09:26:48  ┆           ┆          │
│ mk.gee    ┆ 262cf0ce- ┆ two star  ┆ ec873d45- ┆ … ┆ 173736538 ┆ 2025-01-2 ┆ 174       ┆ 120      │
│           ┆ 2af2-4686 ┆ & the     ┆ a37c-4738 ┆   ┆ 2         ┆ 0         ┆           ┆          │
│           ┆ -a8cc-d6b ┆ dream     ┆ -b817-36d ┆   ┆           ┆ 09:29:42  ┆           ┆          │
│           ┆ 33e…      ┆ police    ┆ 8cc…      ┆   ┆           ┆           ┆           ┆          │
│ bassvicti ┆           ┆ curse is  ┆           ┆ … ┆ 173736554 ┆ 2025-01-2 ┆ 166       ┆ 120      │
│ m         ┆           ┆ lifted    ┆           ┆   ┆ 8         ┆ 0         ┆           ┆          │
│           ┆           ┆ (club     ┆           ┆   ┆           ┆ 09:32:28  ┆           ┆          │
│           ┆           ┆ rmx)      ┆           ┆   ┆           ┆           ┆           ┆          │
│ charli    ┆ 260b6184- ┆ pop 2     ┆ 5414958b- ┆ … ┆ 173736576 ┆ 2025-01-2 ┆ 220       ┆ 120      │
│ xcx       ┆ 8828-48eb ┆           ┆ 12e2-4a6e ┆   ┆ 8         ┆ 0         ┆           ┆          │
│           ┆ -945c-bc4 ┆           ┆ -b335-260 ┆   ┆           ┆ 09:36:08  ┆           ┆          │
│           ┆ cb6…      ┆           ┆ 02c…      ┆   ┆           ┆           ┆           ┆          │
│ snow      ┆ 33243fef- ┆ april     ┆ 3c39c467- ┆ … ┆ 173736597 ┆ 2025-01-2 ┆ 208       ┆ 120      │
│ strippers ┆ ce1a-4ba7 ┆ mixtape 2 ┆ 3e37-4a41 ┆   ┆ 6         ┆ 0         ┆           ┆          │
│           ┆ -a81e-ec7 ┆           ┆ -b530-b68 ┆   ┆           ┆ 09:39:36  ┆           ┆          │
│           ┆ 2e4…      ┆           ┆ 429…      ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ dj tired  ┆           ┆ rest      ┆           ┆ … ┆ 173739814 ┆ 2025-01-2 ┆ 159       ┆ 125      │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 0         ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 18:35:41  ┆           ┆          │
│ travis    ┆ e4a51f17- ┆ astroworl ┆           ┆ … ┆ 173739854 ┆ 2025-01-2 ┆ 401       ┆ 125      │
│ scott     ┆ a57b-47b1 ┆ d         ┆           ┆   ┆ 2         ┆ 0         ┆           ┆          │
│           ┆ -b37b-f55 ┆           ┆           ┆   ┆           ┆ 18:42:22  ┆           ┆          │
│           ┆ 2d0…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ rico      ┆ f7d8f1ce- ┆ iphone    ┆ 4c531ee0- ┆ … ┆ 173739881 ┆ 2025-01-2 ┆ 271       ┆ 125      │
│ nasty     ┆ 6a72-422a ┆           ┆ 9f01-40d0 ┆   ┆ 3         ┆ 0         ┆           ┆          │
│           ┆ -b746-221 ┆           ┆ -b608-068 ┆   ┆           ┆ 18:46:53  ┆           ┆          │
│           ┆ 37b…      ┆           ┆ 3ba…      ┆   ┆           ┆           ┆           ┆          │
│ meat      ┆ 0943f55d- ┆ slept on  ┆ 1ed7783e- ┆ … ┆ 173739897 ┆ 2025-01-2 ┆ 159       ┆ 125      │
│ computer  ┆ 1c10-4a52 ┆ the floor ┆ 2d8d-43e4 ┆   ┆ 2         ┆ 0         ┆           ┆          │
│           ┆ -a1ef-06e ┆ still     ┆ -875e-0b2 ┆   ┆           ┆ 18:49:32  ┆           ┆          │
│           ┆ 625…      ┆ dream…    ┆ 518…      ┆   ┆           ┆           ┆           ┆          │
│ the       ┆ 8f47ae55- ┆ reading   ┆           ┆ … ┆ 173739914 ┆ 2025-01-2 ┆ 175       ┆ 125      │
│ sundays   ┆ 9321-49f1 ┆ writing   ┆           ┆   ┆ 7         ┆ 0         ┆           ┆          │
│           ┆ -b40b-b4e ┆ and arith ┆           ┆   ┆           ┆ 18:52:27  ┆           ┆          │
│           ┆ 067…      ┆ metic     ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [11]:
month = 2
(
    df
    .filter(
        pl.col("track_played_utc").dt.year() == 2025,
        pl.col("track_played_utc").dt.month() == month
    )
    .group_by(
        pl.col("track_played_utc").dt.date(),
        pl.col("track_name"),
        pl.col("artist_name")
    )
    .agg(n_scrobbles = pl.len())
    .with_columns(daily_scrobbles=pl.col("n_scrobbles").sum().over("track_played_utc"))
    # .sort("n_scrobbles", descending=True)
    .sort([ "n_scrobbles", "daily_scrobbles" ], descending=[ True, True ])
    # .row(0, named=True)
)

shape: (1_895, 5)
┌──────────────────┬────────────────────────────────┬──────────────┬─────────────┬─────────────────┐
│ track_played_utc ┆ track_name                     ┆ artist_name  ┆ n_scrobbles ┆ daily_scrobbles │
│ ---              ┆ ---                            ┆ ---          ┆ ---         ┆ ---             │
│ date             ┆ str                            ┆ str          ┆ u32         ┆ u32             │
╞══════════════════╪════════════════════════════════╪══════════════╪═════════════╪═════════════════╡
│ 2025-02-07       ┆ get used to it (losin' it)     ┆ fromtheheart ┆ 10          ┆ 164             │
│ 2025-02-25       ┆ null                           ┆ null         ┆ 9           ┆ 44              │
│ 2025-02-03       ┆ waited all night               ┆ jamie xx     ┆ 6           ┆ 110             │
│ 2025-02-20       ┆ hide away                      ┆ riot shift   ┆ 6           ┆ 104             │
│ 2025-02-24       ┆ with you                       ┆ bassvictim   ┆ 6           ┆ 102             │
│ …                ┆ …                              ┆ …            ┆ …           ┆ …               │
│ 2025-02-05       ┆ bizarre love triangle - 2024   ┆ new order    ┆ 1           ┆ 9               │
│                  ┆ d…                             ┆              ┆             ┆                 │
│ 2025-02-05       ┆ life                           ┆ jamie xx     ┆ 1           ┆ 9               │
│ 2025-02-05       ┆ hum it to google               ┆ bassvictim   ┆ 1           ┆ 9               │
│ 2025-02-05       ┆ butterflies                    ┆ skrillex     ┆ 1           ┆ 9               │
│ 2025-02-05       ┆ qkthr                          ┆ aphex twin   ┆ 1           ┆ 9               │
└──────────────────┴────────────────────────────────┴──────────────┴─────────────┴─────────────────┘

In [12]:
lastfm_df = pl.read_parquet(Path("../data/lastfm/lastfm-listening-2021-2026march.parquet"))
spotify_df = pl.read_parquet(Path("../data/spotify/2017-2021 spotify data.parquet"))
lastfm_df = lastfm_df.with_columns(spotify_track_uri=pl.lit(""))
spotify_df = spotify_df.with_columns(
        artist_mbid=pl.lit(""), album_mbid=pl.lit(""), track_mbid=pl.lit("")
    )
cols = [
        "track_played_utc",
        "date_played_unix",
        "track_name",
        "artist_name",
        "album_name",
        "track_mbid",
        "artist_mbid",
        "album_mbid",
        "spotify_track_uri",
    ]
lastfm_df = lastfm_df.select(cols)
spotify_df = spotify_df.select(cols)

df = lastfm_df.vstack(spotify_df).sort(
    pl.col("date_played_unix"), descending=False
)

In [ ]:
records = (
    df
    .filter(
        pl.col("track_played_utc").dt.year() >= 2021,
        pl.col("track_name").drop_nulls()
    )
    .unique(subset=["track_name"], keep="first")
    .sort("track_played_utc", descending=False)
).to_dicts()

In [15]:
(
    df
    .filter(
        pl.col("track_played_utc").dt.year() >= 2021,
    )
    .unique(subset=["track_name"], keep="first")
    .sort("track_played_utc", descending=False)
    .drop_nulls(pl.col("track_name"))
)

shape: (18_819, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ track_pla ┆ date_play ┆ track_nam ┆ artist_na ┆ … ┆ track_mbi ┆ artist_mb ┆ album_mbi ┆ spotify_ │
│ yed_utc   ┆ ed_unix   ┆ e         ┆ me        ┆   ┆ d         ┆ id        ┆ d         ┆ track_ur │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ i        │
│ datetime[ ┆ i64       ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆ ---      │
│ μs]       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2021-01-0 ┆ 160946012 ┆ NOT FAIR  ┆ The Kid   ┆ … ┆           ┆           ┆           ┆ spotify: │
│ 1         ┆ 5         ┆ (feat.    ┆ LAROI     ┆   ┆           ┆           ┆           ┆ track:2H │
│ 00:15:25  ┆           ┆ Corbin)   ┆           ┆   ┆           ┆           ┆           ┆ rMDMckfC │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ yM4OcZ…  │
│ 2021-01-0 ┆ 160946033 ┆ Her and   ┆ TV Girl   ┆ … ┆           ┆           ┆           ┆ spotify: │
│ 1         ┆ 5         ┆ Her       ┆           ┆   ┆           ┆           ┆           ┆ track:4M │
│ 00:18:55  ┆           ┆ Friend    ┆           ┆   ┆           ┆           ┆           ┆ wYkW85fX │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ hNvV2w…  │
│ 2021-01-0 ┆ 160950483 ┆ Dorothy   ┆ Her's     ┆ … ┆           ┆           ┆           ┆ spotify: │
│ 1         ┆ 5         ┆           ┆           ┆   ┆           ┆           ┆           ┆ track:7j │
│ 12:40:35  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ay75cMfp │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ EIyIkk…  │
│ 2021-01-0 ┆ 160950505 ┆ Punk Monk ┆ Playboi   ┆ … ┆           ┆           ┆           ┆ spotify: │
│ 1         ┆ 0         ┆           ┆ Carti     ┆   ┆           ┆           ┆           ┆ track:5f │
│ 12:44:10  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ SZXFOZfP │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ VW9gvn…  │
│ 2021-01-0 ┆ 160950524 ┆ I hope    ┆ Pity      ┆ … ┆           ┆           ┆           ┆ spotify: │
│ 1         ┆ 6         ┆ that u    ┆ Party     ┆   ┆           ┆           ┆           ┆ track:6z │
│ 12:47:26  ┆           ┆ think of  ┆ (Girls    ┆   ┆           ┆           ┆           ┆ 2EwIB2wT │
│           ┆           ┆ me        ┆ Club)     ┆   ┆           ┆           ┆           ┆ LdXJZ6…  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2026-03-2 ┆ 177428847 ┆ (Somethin ┆ The Micro ┆ … ┆ 17261347- ┆ 6f2f87e7- ┆ 3d341648- ┆          │
│ 3         ┆ 3         ┆ g) - 1    ┆ phones    ┆   ┆ f3fa-40a8 ┆ 3ce9-4f1c ┆ 5aee-4128 ┆          │
│ 17:54:33  ┆           ┆           ┆           ┆   ┆ -81e7-4db ┆ -81dd-6f0 ┆ -805a-a9a ┆          │
│           ┆           ┆           ┆           ┆   ┆ 50d…      ┆ 68a…      ┆ 0ef…      ┆          │
│ 2026-03-2 ┆ 177428936 ┆ I'll Not  ┆ The Micro ┆ … ┆ 20abad51- ┆ 6f2f87e7- ┆ 3d341648- ┆          │
│ 3         ┆ 4         ┆ Contain   ┆ phones    ┆   ┆ 57c0-4a9d ┆ 3ce9-4f1c ┆ 5aee-4128 ┆          │
│ 18:09:24  ┆           ┆ You       ┆           ┆   ┆ -832d-041 ┆ -81dd-6f0 ┆ -805a-a9a ┆          │
│           ┆           ┆           ┆           ┆   ┆ 8fd…      ┆ 68a…      ┆ 0ef…      ┆          │
│ 2026-03-2 ┆ 177428957 ┆ Darkness  ┆ Chris     ┆ … ┆           ┆ 5b7f4511- ┆ 56464592- ┆          │
│ 3         ┆ 1         ┆           ┆ Stussy    ┆   ┆           ┆ 1764-4d80 ┆ 69b9-4ceb ┆          │
│ 18:12:51  ┆           ┆           ┆           ┆   ┆           ┆ -83b5-8c1 ┆ -8b58-705 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 50f…      ┆ e18…      ┆          │
│ 2026-03-2 ┆ 177435620 ┆ Soul      ┆ Dalton    ┆ … ┆ 0b91a630- ┆ d7806b58- ┆           ┆          │
│ 4         ┆ 2         ┆ Brother   ┆           ┆   ┆ 0561-413d ┆ 63e9-4875 ┆           ┆          │
│ 12:43:22  ┆           ┆           ┆           ┆   ┆ -aee0-c81 ┆ -b49b-728 ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 6c1…      ┆ 717…      ┆           ┆          │
│ 2026-03-2 ┆ 177444757 ┆ I Love    ┆ Donna     ┆ … ┆           ┆ ba7c4a1c- ┆ 2545dab2- ┆          │
│ 5         ┆ 0         ┆ You       ┆ Lewis     ┆   ┆           ┆ aa4e-488a ┆ b8d7-4197 ┆          │
│ 14:06:10  ┆           ┆ Always    ┆           ┆   ┆           ┆ -92dc-be9 ┆ -97ac-a7d ┆          │
│           ┆           ┆ Forever   ┆           ┆   ┆           ┆ 2cb…      ┆ 8d1…      ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘